import type { Article } from "./articles";

const openAiPublishers = "https://help.openai.com/pt-br/articles/12627856-publishers-and-developers-faq";
const openAiSearch = "https://help.openai.com/pt-br/articles/9237897-pesquisa-do-chatgpt";
const googleAi = "https://developers.google.com/search/docs/appearance/ai-features";
const googleStructured = "https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data";
const googleOrg = "https://developers.google.com/search/docs/appearance/structured-data/organization";
const googleCanonical = "https://developers.google.com/search/docs/crawling-indexing/canonicalization";
const googleHelpful = "https://developers.google.com/search/docs/fundamentals/creating-helpful-content";

export const searchAiOpsArticles: Record<string, Article> = {
  "chatgpt-nao-cita-meu-site": {
    slug: "chatgpt-nao-cita-meu-site",
    title: "O ChatGPT não cita meu site: o que auditar antes de tentar 'otimizar para IA'",
    metaTitle: "ChatGPT Não Cita Meu Site? Checklist de Diagnóstico | AUDITSEO",
    description: "Playbook para diagnosticar ausência de citações no ChatGPT: OAI-SearchBot, acesso, páginas, intenção, citabilidade, entidade, fontes externas e medição sem prometer resultado.",
    eyebrow: "DIAGNÓSTICO SEARCH AI",
    publishedAt: "2026-09-07",
    updatedAt: "2026-09-07",
    readTime: "14 min",
    author: "Sidney Santos",
    authorUrl: "/autor/sidney-santos",
    directAnswer: "Se o ChatGPT não cita seu site, não comece por schema, FAQs em massa ou llms.txt. Primeiro verifique se o conteúdo é elegível para descoberta, se a página certa existe para a intenção, se a informação é clara e verificável e se o domínio possui evidências que sustentem a resposta. A OpenAI informa que permitir o OAI-SearchBot é uma condição controlável para elegibilidade na busca, mas não garante citação nem posicionamento.",
    takeaways: [
      "Ausência de citação pode ocorrer em etapas diferentes; tratá-la como um único problema leva a ações erradas.",
      "Bloqueio de OAI-SearchBot é um problema técnico verificável, mas liberar o crawler não cria garantia de citação.",
      "Uma página pode ser acessível e ainda não ser a melhor fonte para a pergunta observada.",
      "Citabilidade exige respostas específicas, autoria, evidência, contexto e informação verificável.",
      "O diagnóstico precisa usar prompts congelados e repetição; uma pergunta isolada não é baseline.",
    ],
    blocks: [
      { type: "heading", text: "Primeiro: descubra em qual etapa a citação está falhando" },
      { type: "paragraph", text: "A pergunta 'por que o ChatGPT não cita meu site?' costuma pular direto para a tática. O diagnóstico mais útil é localizar a primeira dependência quebrada: acesso, recuperação, entendimento, confiança ou citabilidade." },
      { type: "list", items: [
        "Acesso: o OAI-SearchBot consegue rastrear a página e o host/CDN aceita o tráfego publicado pela OpenAI?",
        "Recuperação: existe uma página que realmente responde à intenção observada?",
        "Entendimento: fica claro qual entidade, serviço, pessoa e contexto a página representa?",
        "Confiança: há autoria, provas, fontes e consistência suficientes para sustentar as afirmações?",
        "Citabilidade: a página contém informação específica que pode sustentar uma resposta, ou apenas copy comercial genérica?",
      ] },
      { type: "heading", text: "1. Audite elegibilidade técnica" },
      { type: "paragraph", text: "A documentação atual da OpenAI diz que qualquer site público pode aparecer na busca do ChatGPT e orienta sites que desejam ser encontrados, exibidos e citados a não bloquear o OAI-SearchBot. Também é necessário garantir que hospedagem, WAF ou CDN não bloqueiem os endereços publicados do bot." },
      { type: "callout", title: "O limite da evidência", text: "Isso permite afirmar que o bloqueio pode impedir elegibilidade. Não permite afirmar que liberar o bot fará uma página ser citada em determinado prompt." },
      { type: "heading", text: "2. Verifique se existe uma página digna de recuperação" },
      { type: "paragraph", text: "Sites frequentemente tentam resolver ausência em IA sem possuir uma página que responda à pergunta. Uma home institucional não substitui páginas específicas de serviço, comparações, definições, estudos, documentação ou respostas técnicas quando essas são as intenções pesquisadas." },
      { type: "list", items: [
        "a pergunta central aparece de forma explícita?",
        "a resposta principal chega cedo, sem depender de navegação ou interação?",
        "a página diferencia fato, opinião, método próprio e informação de terceiros?",
        "há links para evidências e fontes primárias quando a afirmação depende de plataforma?",
        "o conteúdo oferece algo que uma síntese genérica não entrega?",
      ] },
      { type: "heading", text: "3. Teste citabilidade, não apenas 'qualidade de SEO'" },
      { type: "paragraph", text: "Uma página pode ter title, H1 e links internos corretos e ainda oferecer pouco material citável. Na metodologia AUDITSEO, citabilidade significa ser específica, verificável, atribuível e suficientemente clara para funcionar como fonte. É um framework editorial nosso, não um fator oficial publicado pela OpenAI." },
      { type: "heading", text: "4. Compare fontes que aparecem no lugar do seu domínio" },
      { type: "paragraph", text: "Quando a resposta cita concorrentes, documentação oficial, imprensa, fóruns ou diretórios, o diagnóstico deve perguntar por que essas fontes resolvem melhor a necessidade informacional. Isso é mais útil do que copiar superficialmente o formato de uma página citada." },
      { type: "heading", text: "5. Audite a entidade fora do próprio site" },
      { type: "paragraph", text: "A empresa pode ser bem descrita no domínio e ainda aparecer de forma fraca ou inconsistente em fontes externas. Nome, especialidade, fundadores, serviços, localização, provas e histórico precisam ser verificáveis no ecossistema — sem fabricar menções." },
      { type: "heading", text: "6. Construa um baseline reproduzível" },
      { type: "paragraph", text: "Selecione prompts por intenção, registre plataforma, data, idioma, contexto e repetição e classifique menção, citação, recomendação, domínio citado e precisão da descrição. Só então existe base para dizer que algo melhorou." },
      { type: "callout", title: "Ordem de prioridade", text: "Acesso → página/intenção → entendimento → evidência → citabilidade → validação externa → medição. Pular etapas tende a produzir GEO theater." },
    ],
    sources: [
      { label: "OpenAI — Editores e desenvolvedores — FAQ", url: openAiPublishers, note: "Orientações atuais sobre OAI-SearchBot, descoberta, citação e controle de acesso." },
      { label: "OpenAI — Busca do ChatGPT", url: openAiSearch, note: "A OpenAI afirma que a classificação usa múltiplos fatores e que posicionamento não é garantido." },
      { label: "Google — conteúdo útil e confiável", url: googleHelpful, note: "Referência complementar sobre autoria, evidência e valor editorial people-first." },
    ],
    relatedServices: [["Generative Search Readiness", "/solucoes/geo-ia-readiness"], ["Intent Content Architecture", "/solucoes/conteudo-por-intencao"], ["Entity Authority", "/solucoes/autoridade-de-entidade"]],
  },

  "site-indexado-mas-ausente-em-search-ai": {
    slug: "site-indexado-mas-ausente-em-search-ai",
    title: "Meu site está indexado no Google, mas não aparece nas respostas de IA: por quê?",
    metaTitle: "Site Indexado mas Ausente em IA: Como Diagnosticar | AUDITSEO",
    description: "Entenda por que indexação no Google não garante recuperação, menção ou citação em Search AI e como auditar intenção, entidade, evidência, fontes e elegibilidade por plataforma.",
    eyebrow: "INDEXAR NÃO É SER RECUPERADO",
    publishedAt: "2026-09-07",
    updatedAt: "2026-09-07",
    readTime: "13 min",
    author: "Sidney Santos",
    authorUrl: "/autor/sidney-santos",
    directAnswer: "Estar indexado no Google prova apenas que uma URL entrou no índice do Google sob determinadas condições. Isso não garante que a página será recuperada para uma consulta específica, muito menos mencionada ou citada por uma interface de IA que pode usar mecanismos, índices e fontes diferentes. O diagnóstico precisa separar Index de Retrieve, Understand, Trust e Cite.",
    takeaways: [
      "Indexação é uma condição necessária para certos fluxos de Google Search, não uma promessa de recuperação em qualquer pergunta.",
      "ChatGPT Search possui regras próprias de elegibilidade e descoberta, incluindo OAI-SearchBot.",
      "A mesma página pode estar indexada e ser semanticamente inadequada para a intenção que você está testando.",
      "Canonicalização, duplicação e conteúdo pouco distinto podem reduzir clareza sobre qual URL deve representar o tema.",
      "Search AI precisa ser medida por plataforma e prompt; não existe um status universal 'indexado na IA'.",
    ],
    blocks: [
      { type: "heading", text: "Indexação e recuperação são etapas diferentes" },
      { type: "paragraph", text: "O Google descreve canonicalização e indexação como processos de seleção e armazenamento de URLs representativas. Mesmo dentro do Google, estar indexado não significa que a URL será mostrada para toda consulta. Quando passamos para Search AI, a distância aumenta: cada interface pode usar mecanismos próprios de recuperação, fontes e critérios." },
      { type: "heading", text: "1. Confirme o que 'indexado' realmente significa" },
      { type: "list", items: [
        "qual URL o Google considera canônica?",
        "a página está indexada ou apenas descoberta?",
        "o conteúdo principal é suficientemente distinto de páginas semelhantes?",
        "há noindex, canonicals conflitantes, redirects ou renderização que mudam a interpretação?",
      ] },
      { type: "paragraph", text: "O Google ressalta que rel=canonical é um sinal e pode escolher outra URL quando seus sistemas consideram outra página mais representativa. Portanto, 'a URL existe no sitemap' não equivale automaticamente a 'esta é a fonte principal reconhecida'." },
      { type: "heading", text: "2. Verifique a elegibilidade da plataforma de IA separadamente" },
      { type: "paragraph", text: "Para ChatGPT Search, a OpenAI orienta permitir OAI-SearchBot e o tráfego dos IPs publicados. Isso mostra por que usar apenas 'site:dominio no Google' como teste de readiness para IA é insuficiente." },
      { type: "heading", text: "3. Avalie correspondência entre página e intenção" },
      { type: "paragraph", text: "Uma página pode ranquear ou estar indexada para a marca e ainda não responder perguntas de categoria, comparação ou solução de problema. Search AI tende a expor essa lacuna porque usuários formulam perguntas completas, não apenas keywords curtas." },
      { type: "heading", text: "4. Reduza ambiguidade de entidade" },
      { type: "paragraph", text: "Se a página não deixa explícito quem presta o serviço, para quem, em qual mercado, com quais especialistas e quais evidências, o sistema pode recuperar uma fonte mais clara. Entity Home, páginas de especialistas, serviços e provas ajudam a tornar a organização mais verificável." },
      { type: "heading", text: "5. Compare a qualidade informacional das fontes citadas" },
      { type: "paragraph", text: "Quando outras fontes aparecem, catalogue formato, especificidade, dados, autoria, atualização e evidências. O objetivo não é imitar layout: é descobrir qual necessidade informacional elas resolvem melhor." },
      { type: "heading", text: "6. Não trate ausência como prova de penalização" },
      { type: "paragraph", text: "Uma marca ausente em uma execução pode aparecer na seguinte. Respostas generativas variam e interfaces mudam. O correto é repetir prompts fixos e observar padrões, não inferir uma penalização a partir de um único resultado." },
      { type: "callout", title: "Framework AUDITSEO", text: "Index é apenas a segunda etapa. O diagnóstico continua por Retrieve → Understand → Trust → Cite. Uma página indexada pode falhar em qualquer uma delas." },
    ],
    sources: [
      { label: "Google Search Central — canonicalização", url: googleCanonical, note: "Explica como o Google seleciona URLs representativas e por que a canonical indicada é um sinal, não uma ordem absoluta." },
      { label: "OpenAI — Editores e desenvolvedores — FAQ", url: openAiPublishers, note: "Mostra que ChatGPT Search possui sua própria condição de descoberta via OAI-SearchBot." },
      { label: "Google Search Central — AI features", url: googleAi, note: "Reforça que fundamentos de Search continuam relevantes para recursos de IA no Google." },
    ],
    relatedServices: [["Organic Activation", "/solucoes/site-sem-tracao"], ["Generative Search Readiness", "/solucoes/geo-ia-readiness"], ["Search Foundation", "/solucoes/projetos-comecando-do-zero"]],
  },

  "schema-ajuda-aparecer-no-chatgpt": {
    slug: "schema-ajuda-aparecer-no-chatgpt",
    title: "Schema ajuda a aparecer no ChatGPT? O papel real dos dados estruturados em Search AI",
    metaTitle: "Schema Ajuda a Aparecer no ChatGPT? O Papel Real | AUDITSEO",
    description: "Entenda o que structured data faz no Google, por que schema não cria autoridade nem garante citação por IA e quando Organization, Person e outros markups realmente ajudam a clareza da entidade.",
    eyebrow: "SCHEMA SEM HYPE",
    publishedAt: "2026-09-07",
    updatedAt: "2026-09-07",
    readTime: "11 min",
    author: "Sidney Santos",
    authorUrl: "/autor/sidney-santos",
    directAnswer: "Schema pode ajudar mecanismos compatíveis a interpretar informações estruturadas quando o markup representa corretamente o conteúdo visível, mas não há base pública para tratá-lo como botão para aparecer no ChatGPT. O Google documenta structured data para seus próprios recursos e afirma que não existe schema especial necessário para AI Overviews ou AI Mode. A OpenAI não documenta schema.org como requisito de elegibilidade ou garantia de citação no ChatGPT Search.",
    takeaways: [
      "Structured data representa informação; não cria reputação, experiência ou prova.",
      "O Google exige que o markup corresponda ao conteúdo visível e às diretrizes do tipo utilizado.",
      "Para recursos de IA no Google, a orientação atual não exige schema especial adicional.",
      "A documentação pública da OpenAI enfatiza acesso do OAI-SearchBot, não um tipo de schema para ganhar citação.",
      "Organization, Person/Profile e relações coerentes continuam úteis para arquitetura de entidade quando refletem fatos reais.",
    ],
    blocks: [
      { type: "heading", text: "O erro mais comum: confundir representação com autoridade" },
      { type: "paragraph", text: "JSON-LD pode declarar nome, organização, pessoa, logo, serviço e relações. Isso não torna uma empresa especialista nem valida uma afirmação. Schema é uma camada de representação estruturada; confiança continua dependendo do conteúdo e das evidências disponíveis." },
      { type: "heading", text: "O que o Google documenta sobre structured data" },
      { type: "paragraph", text: "O Google usa structured data para compreender conteúdo e tornar páginas elegíveis a determinados rich results. As diretrizes exigem consistência com o conteúdo visível e não prometem que um recurso será exibido mesmo quando o markup está correto." },
      { type: "paragraph", text: "Na documentação específica de AI features, o Google afirma que não é necessário criar schema especial para AI Overviews ou AI Mode. Isso invalida a promessa de um 'schema secreto para IA' dentro do ecossistema Google." },
      { type: "heading", text: "E no ChatGPT?" },
      { type: "paragraph", text: "A documentação pública atual da OpenAI para publishers fala de site público, OAI-SearchBot, acesso, noindex e compatibilidade de descoberta. Ela não apresenta schema.org como requisito para inclusão nem como alavanca garantida de citação." },
      { type: "heading", text: "Quando schema é útil na arquitetura de entidade" },
      { type: "list", items: [
        "Organization para explicitar dados institucionais coerentes com a página",
        "Person/ProfilePage para conectar especialistas, autoria e organização quando aplicável",
        "Breadcrumb para explicitar hierarquia de navegação",
        "Article para representar autoria, datas e publicação de documentos editoriais",
        "tipos específicos suportados quando a página realmente cumpre os requisitos do recurso",
      ] },
      { type: "heading", text: "Quando schema vira theater" },
      { type: "list", items: [
        "quando declara credenciais que a página não comprova",
        "quando sameAs aponta indiscriminadamente para perfis sem relevância ou consistência",
        "quando dezenas de tipos são adicionados apenas para aumentar 'pontuação' de ferramenta",
        "quando schema recebe prioridade enquanto páginas importantes continuam fracas, duplicadas ou não indexáveis",
        "quando o markup é vendido como garantia de aparecer no ChatGPT ou no Google AI",
      ] },
      { type: "heading", text: "Como a AUDITSEO prioriza structured data" },
      { type: "paragraph", text: "Primeiro definimos a entidade e o conteúdo visível. Depois usamos structured data para formalizar relações que já são verdadeiras e úteis. O markup é consequência da arquitetura, não substituto dela." },
      { type: "callout", title: "Regra simples", text: "Se remover o JSON-LD fizer a página deixar de explicar quem é a empresa, o problema está no conteúdo. O usuário e os sistemas precisam encontrar a informação no documento, não apenas no script." },
    ],
    sources: [
      { label: "Google — Introdução a structured data", url: googleStructured, note: "Documentação sobre função, elegibilidade e limitações de dados estruturados no Google Search." },
      { label: "Google — Organization structured data", url: googleOrg, note: "Exemplo de representação de organização e requisitos aplicáveis." },
      { label: "Google — AI features and your website", url: googleAi, note: "Afirma que não é necessário schema especial para aparecer nos recursos de IA do Google Search." },
      { label: "OpenAI — Editores e desenvolvedores — FAQ", url: openAiPublishers, note: "Documenta condições públicas de descoberta no ChatGPT Search sem declarar schema.org como requisito." },
    ],
    relatedServices: [["Entity Authority", "/solucoes/autoridade-de-entidade"], ["Search Foundation", "/solucoes/projetos-comecando-do-zero"], ["Generative Search Readiness", "/solucoes/geo-ia-readiness"]],
  },

  "como-medir-se-geo-esta-funcionando": {
    slug: "como-medir-se-geo-esta-funcionando",
    title: "Como medir se GEO está funcionando sem inventar um 'AI Visibility Score'",
    metaTitle: "Como Medir GEO e Visibilidade em IA com Método | AUDITSEO",
    description: "Framework para medir GEO e Search AI com prompts congelados, repetição, Mention Rate, Citation Rate, Recommendation Rate, Entity Accuracy, referrals e limites de causalidade.",
    eyebrow: "MENSURAÇÃO GEO",
    publishedAt: "2026-09-07",
    updatedAt: "2026-09-07",
    readTime: "15 min",
    author: "Sidney Santos",
    authorUrl: "/autor/sidney-santos",
    directAnswer: "GEO só pode ser avaliado com um baseline reproduzível. Congele prompts por intenção, plataformas e contexto; repita as execuções; classifique separadamente menção, citação, recomendação, fontes, precisão da entidade e referrals observáveis; e compare ciclos. Não atribua automaticamente uma mudança a uma intervenção de GEO, porque correlação temporal não prova causalidade.",
    takeaways: [
      "Não existe uma única métrica que represente toda a presença em Search AI.",
      "Menção, citação e recomendação precisam ser classificadas separadamente.",
      "Prompts escolhidos depois do resultado invalidam o benchmark.",
      "Repetição é necessária porque respostas generativas variam.",
      "Referral de IA é útil, mas não captura toda influência de respostas sem clique.",
    ],
    blocks: [
      { type: "heading", text: "Antes de medir, defina o evento que importa" },
      { type: "paragraph", text: "'Aparecer na IA' mistura fenômenos diferentes. Uma marca pode ser mencionada sem fonte, citada como fonte, recomendada como opção ou descrita corretamente em um prompt branded. O primeiro passo é não condensar eventos distintos em um número de vaidade." },
      { type: "list", items: [
        "Mention Rate: proporção de prompts válidos em que a marca é mencionada",
        "Citation Rate: proporção em que uma fonte oficial ou externa associada à marca é citada",
        "Recommendation Rate: proporção em que a marca é apresentada como opção apropriada",
        "Entity Accuracy: precisão com que identidade, oferta e contexto são descritos",
        "Source Share: distribuição dos domínios que sustentam respostas",
        "Referral: tráfego identificável vindo de interfaces de IA quando observável",
      ] },
      { type: "heading", text: "1. Congele o universo de prompts antes da coleta" },
      { type: "paragraph", text: "Defina famílias de intenção, texto dos prompts, idioma, mercado, plataformas e marcas avaliadas antes da primeira execução. Se o prompt muda porque uma resposta ficou ruim, você não está medindo evolução; está escolhendo a amostra." },
      { type: "heading", text: "2. Separe prompts genéricos de prompts branded" },
      { type: "paragraph", text: "Prompts de categoria medem descoberta e competição. Prompts branded medem precisão da entidade. Misturar os dois tende a inflar presença de marcas conhecidas e produz um score pouco interpretável." },
      { type: "heading", text: "3. Registre repetição e variabilidade" },
      { type: "paragraph", text: "Uma execução é uma observação, não uma verdade permanente. Guarde respostas contraditórias, registre data e repita a amostra. A variabilidade é parte do fenômeno e não deve ser apagada do relatório." },
      { type: "heading", text: "4. Mapeie as fontes, não só a marca" },
      { type: "paragraph", text: "Se a empresa aparece, registre se o sistema cita o domínio oficial, uma matéria, diretório, comunidade, documento público ou concorrente. A composição das fontes revela oportunidades de conteúdo e autoridade que uma taxa de menção isolada esconde." },
      { type: "heading", text: "5. Conecte Search AI a métricas do site" },
      { type: "paragraph", text: "A OpenAI informa que referrals do ChatGPT podem ser identificáveis em analytics. Quando houver tráfego observável, conecte origem a landing page, comportamento e conversão — sem assumir que toda influência de IA produz clique." },
      { type: "heading", text: "6. Não transforme antes/depois em causalidade" },
      { type: "paragraph", text: "Se Citation Rate sobe depois de melhorar uma página, a sequência temporal é interessante, mas não prova que a intervenção causou a mudança. Modelos, índices, fontes e comportamento competitivo também mudam. O relatório precisa separar observação de hipótese causal." },
      { type: "heading", text: "O mínimo para um dashboard defensável" },
      { type: "list", items: [
        "versão do estudo e ciclo",
        "prompt_id e família de intenção",
        "plataforma/modo de busca",
        "data e número da repetição",
        "marcas mencionadas e recomendadas",
        "URLs e domínios citados",
        "labels de Entity Accuracy",
        "status de revisão humana",
        "comparação com baseline e limitações do ciclo",
      ] },
      { type: "callout", title: "Princípio AUDITSEO", text: "Um benchmark menor, congelado e auditável é mais útil do que um 'AI Visibility Score' grande cuja amostra, pesos e classificação ninguém consegue reconstruir." },
    ],
    sources: [
      { label: "OpenAI — Busca do ChatGPT", url: openAiSearch, note: "Documenta busca, elegibilidade e ausência de garantia de posicionamento." },
      { label: "OpenAI — Editores e desenvolvedores — FAQ", url: openAiPublishers, note: "Inclui orientação sobre descoberta e attribution/referrals quando observáveis." },
      { label: "Google — AI features and your website", url: googleAi, note: "Contexto oficial sobre como o Google enquadra seus recursos de IA dentro dos fundamentos de Search." },
      { label: "AUDITSEO — Protocolo de benchmark Search AI", url: "https://www.auditseo.com.br/blog/protocolo-benchmark-search-ai", note: "Metodologia própria publicada antes da coleta de dados proprietários." },
    ],
    relatedServices: [["Generative Search Readiness", "/solucoes/geo-ia-readiness"], ["Organic Evolution Cycle", "/solucoes/evolucao-organica"], ["Entity Authority", "/solucoes/autoridade-de-entidade"]],
  },
};

export const searchAiOpsArticleList = Object.values(searchAiOpsArticles);
