import type { Article } from "./articles";

const googleHireSeo = "https://developers.google.com/search/docs/fundamentals/do-i-need-seo?hl=pt-BR";
const googleThirdParty = "https://developers.google.com/search/docs/fundamentals/third-party-seo?hl=pt-br";
const googleCrawling = "https://developers.google.com/search/docs/crawling-indexing";
const googleTechnical = "https://developers.google.com/search/docs/essentials/technical";
const googleHelpful = "https://developers.google.com/search/docs/fundamentals/creating-helpful-content";

export const buyerOpsArticles: Record<string, Article> = {
  "o-que-consultoria-seo-deve-entregar": {
    slug: "o-que-consultoria-seo-deve-entregar",
    title: "O que uma consultoria de SEO deve entregar? O que muda conforme o problema",
    metaTitle: "O que uma Consultoria de SEO Deve Entregar? | AUDITSEO",
    description: "Entenda quais entregáveis fazem sentido em consultoria SEO, por que não existe checklist universal e como diagnóstico, roadmap, documentação, implementação e validação devem se conectar.",
    eyebrow: "DECISÃO DE CONTRATAÇÃO",
    publishedAt: "2026-09-07",
    updatedAt: "2026-09-07",
    readTime: "13 min",
    author: "Sidney Santos",
    authorUrl: "/autor/sidney-santos",
    directAnswer: "Uma consultoria de SEO deve entregar clareza sobre o problema, evidências que sustentam o diagnóstico, prioridades, recomendações explicadas, responsáveis, critérios de validação e acompanhamento dos resultados. O formato muda conforme o cenário: um site novo precisa de arquitetura e requisitos; uma queda precisa de investigação; uma migração precisa de mapa de risco; um programa contínuo precisa de backlog e aprendizado. Um pacote fixo de entregáveis não substitui diagnóstico.",
    takeaways: [
      "O principal entregável de uma consultoria não é um PDF: é uma decisão tecnicamente defensável.",
      "Auditoria, roadmap e implementação precisam estar conectados ao problema original.",
      "O Google recomenda transparência sobre mudanças, lógica das recomendações e estimativas realistas de melhoria e trabalho.",
      "Entregáveis devem variar por cenário; repetir o mesmo checklist para todos os clientes é um sinal de baixa personalização.",
      "Mensuração precisa responder se o gargalo original mudou, não apenas se tarefas foram concluídas.",
    ],
    blocks: [
      { type: "heading", text: "O erro de comprar SEO pela quantidade de entregáveis" },
      { type: "paragraph", text: "Propostas costumam competir por volume: auditoria, palavras-chave, relatórios, links, artigos, schema, dashboards. O problema é que uma lista longa pode parecer completa e ainda não dizer qual causa será atacada." },
      { type: "paragraph", text: "O Google recomenda avaliar se o profissional entende o negócio, explica o raciocínio, comunica as mudanças e oferece estimativas realistas. Isso coloca a qualidade da decisão acima da quantidade de itens em um pacote." },
      { type: "heading", text: "1. Diagnóstico com evidência" },
      { type: "list", items: [
        "baseline de tráfego, consultas, páginas e conversões relevantes",
        "estado de rastreamento, indexação e renderização quando aplicável",
        "mapa de intenção e páginas prioritárias",
        "hipóteses competitivas e editoriais",
        "separação entre fato observado, hipótese e recomendação",
      ] },
      { type: "heading", text: "2. Priorização, não apenas lista de problemas" },
      { type: "paragraph", text: "Uma consultoria útil precisa dizer o que fazer primeiro, o que pode esperar e o que não deve ser feito. Impacto, risco, esforço, dependências e proximidade comercial devem entrar na priorização." },
      { type: "heading", text: "3. Recomendação explicada" },
      { type: "paragraph", text: "Toda mudança relevante precisa de racional: qual problema resolve, qual evidência a sustenta, quem implementa, qual risco existe e como validar. Isso vale para redirects, canonicals, páginas novas, consolidação de conteúdo, schema, arquitetura e ações de autoridade." },
      { type: "heading", text: "4. Entregáveis variam pelo cenário" },
      { type: "list", items: [
        "site novo: arquitetura, requisitos de indexação, templates, entidades, medição e QA",
        "site sem tração: diagnóstico de cobertura, intenção, qualidade, autoridade e conversão",
        "queda orgânica: segmentação do impacto, timeline, hipóteses causais e plano de recuperação",
        "migração: inventário, equivalência de URLs, redirects, smoke e monitoramento",
        "Search AI: prompt baseline, fontes, elegibilidade, citabilidade e Entity Accuracy",
        "operação madura: opportunity backlog, decay, prioridades e Learning Loop",
      ] },
      { type: "heading", text: "5. Implementação ou governança da implementação" },
      { type: "paragraph", text: "Se a consultoria não implementa diretamente, ela precisa deixar requisitos suficientemente claros para desenvolvimento, conteúdo, PR ou analytics. Um backlog sem dono e sem critério de aceite não é execução." },
      { type: "heading", text: "6. Validação pós-implementação" },
      { type: "paragraph", text: "Mudança publicada não significa mudança correta. A consultoria deve validar status, renderização, canonical, links, páginas, analytics e sinais esperados quando relevantes ao escopo." },
      { type: "heading", text: "7. Relatório de aprendizado" },
      { type: "paragraph", text: "O acompanhamento precisa registrar o que mudou, o que não mudou, quais hipóteses perderam força e quais prioridades surgiram. Relatório mensal que apenas repete rankings e sessões não substitui um ciclo de decisão." },
      { type: "callout", title: "Critério AUDITSEO", text: "Um bom entregável permite que outra pessoa entenda o diagnóstico, a decisão, a implementação e o critério de validação sem depender da memória de uma reunião." },
    ],
    sources: [
      { label: "Google Search Central — Você precisa de SEO?", url: googleHireSeo, note: "O Google recomenda avaliar transparência, lógica das mudanças, referências, interesse pelo negócio e estimativas realistas." },
      { label: "Google — serviços e conselhos de terceiros", url: googleThirdParty, note: "Orientação para validar recomendações de terceiros contra documentação oficial e desconfiar de claims sem base." },
    ],
    relatedServices: [["Search Foundation", "/solucoes/projetos-comecando-do-zero"], ["Organic Activation", "/solucoes/site-sem-tracao"], ["Organic Evolution Cycle", "/solucoes/evolucao-organica"]],
  },

  "auditoria-seo-o-que-deve-conter": {
    slug: "auditoria-seo-o-que-deve-conter",
    title: "Auditoria SEO: o que deve conter para virar decisão — e não apenas uma lista de erros",
    metaTitle: "Auditoria SEO: O que Deve Conter? Checklist com Prioridade | AUDITSEO",
    description: "Veja o que uma auditoria SEO útil deve analisar: crawl, indexação, arquitetura, conteúdo, intenção, autoridade, dados, riscos, priorização, roadmap e validação.",
    eyebrow: "AUDITORIA SEO",
    publishedAt: "2026-09-07",
    updatedAt: "2026-09-07",
    readTime: "15 min",
    author: "Sidney Santos",
    authorUrl: "/autor/sidney-santos",
    directAnswer: "Uma auditoria SEO útil deve conectar evidências técnicas, conteúdo, intenção, autoridade e dados de performance a decisões priorizadas. Ela precisa explicar o que foi observado, por que importa, qual hipótese existe, qual ação é recomendada, quem depende dela e como validar o resultado. Exportar erros de um crawler ou score de ferramenta não é suficiente.",
    takeaways: [
      "Crawler é fonte de evidência, não diagnóstico completo.",
      "A auditoria precisa considerar Search Console, analytics e contexto de negócio sempre que disponíveis.",
      "HTTP, crawl, indexação, canonical, links e renderização formam a fundação técnica.",
      "Conteúdo e intenção precisam ser avaliados junto com arquitetura e entidades.",
      "O resultado final deve ser um roadmap priorizado com risco, esforço, impacto e validação.",
    ],
    blocks: [
      { type: "heading", text: "Uma auditoria não deve começar pelo score da ferramenta" },
      { type: "paragraph", text: "Ferramentas conseguem detectar padrões úteis, mas o próprio Google lembra que ferramentas de terceiros não possuem acesso aos dados internos de ranking e não são endossadas pela Pesquisa Google. A auditoria precisa interpretar evidências, não terceirizar decisão para um score." },
      { type: "heading", text: "1. Baseline e contexto" },
      { type: "list", items: [
        "objetivo comercial e páginas que sustentam receita",
        "consultas e segmentos prioritários",
        "histórico de tráfego, impressões, cliques e conversões",
        "mudanças recentes de CMS, domínio, templates, conteúdo ou tracking",
        "mercados, localidades, produtos e concorrentes relevantes",
      ] },
      { type: "heading", text: "2. Crawl e resposta do servidor" },
      { type: "paragraph", text: "Status HTTP, redirects, cadeias, 404, 5xx, robots, renderização e disponibilidade precisam ser auditados porque páginas precisam funcionar antes de qualquer discussão de relevância." },
      { type: "heading", text: "3. Indexação e canonicalização" },
      { type: "list", items: [
        "URLs indexáveis vs noindex",
        "canonical declarado vs sinais conflitantes",
        "sitemaps e URLs submetidas",
        "duplicação e páginas pouco distintas",
        "URLs válidas que não entram no índice esperado",
      ] },
      { type: "heading", text: "4. Arquitetura e links internos" },
      { type: "paragraph", text: "A auditoria deve verificar se páginas prioritárias são encontráveis, recebem contexto interno e ocupam uma posição coerente na arquitetura. Profundidade e links importam quando ajudam usuários e crawlers a descobrir e compreender relações." },
      { type: "heading", text: "5. Intenção, conteúdo e sobreposição" },
      { type: "list", items: [
        "qual intenção cada URL deve possuir",
        "lacunas de páginas para decisões importantes",
        "canibalização real vs sobreposição legítima",
        "conteúdo commodity, desatualizado ou sem evidência",
        "páginas comerciais sem sustentação temática",
      ] },
      { type: "heading", text: "6. Entidade, autoria e confiança" },
      { type: "paragraph", text: "Especialistas, organização, serviços, provas, fontes externas e structured data coerente podem participar do diagnóstico quando clareza e confiança são relevantes. Schema não deve ser auditado isoladamente do conteúdo que representa." },
      { type: "heading", text: "7. Search AI quando fizer parte do problema" },
      { type: "paragraph", text: "Se a empresa quer medir presença em IA, a auditoria deve incluir elegibilidade de crawlers documentados, prompts congelados, fontes observadas, menções, citações e precisão da entidade — sem inventar um score universal." },
      { type: "heading", text: "8. Priorização e roadmap" },
      { type: "paragraph", text: "O relatório final precisa ordenar ações. Uma forma defensável é registrar impacto esperado, evidência, esforço, risco, dependências, responsável e critério de aceite. Sem priorização, uma auditoria grande pode reduzir velocidade em vez de aumentá-la." },
      { type: "heading", text: "9. O que deve acompanhar cada achado" },
      { type: "list", items: [
        "evidência ou exemplo reproduzível",
        "escopo afetado",
        "impacto potencial e nível de confiança",
        "recomendação",
        "dependências e risco",
        "responsável sugerido",
        "como testar se foi corrigido",
      ] },
      { type: "callout", title: "Diferença essencial", text: "Crawl report diz o que uma ferramenta encontrou. Auditoria explica o que isso significa para o negócio, o que fazer primeiro e como saber se a decisão funcionou." },
    ],
    sources: [
      { label: "Google — Você precisa de SEO?", url: googleHireSeo, note: "O Google recomenda auditorias com estimativas realistas de melhoria e trabalho e alerta contra garantias de primeira posição." },
      { label: "Google — crawling e indexing", url: googleCrawling, note: "Base oficial para rastreamento, indexação, robots, links, sitemaps e mudanças de site." },
      { label: "Google — requisitos técnicos", url: googleTechnical, note: "Documenta requisitos básicos como HTTP 200 e conteúdo indexável." },
      { label: "Google — conteúdo útil", url: googleHelpful, note: "Referência para qualidade, autoria, utilidade e valor editorial." },
      { label: "Google — orientações sobre terceiros", url: googleThirdParty, note: "Alerta sobre extrapolações de ferramentas e conselhos de SEO de terceiros." },
    ],
    relatedServices: [["Search Foundation", "/solucoes/projetos-comecando-do-zero"], ["Organic Activation", "/solucoes/site-sem-tracao"], ["Search Recovery", "/solucoes/recuperacao-organica"]],
  },
};

export const buyerOpsArticleList = Object.values(buyerOpsArticles);
