import type { Article } from "./articles";

const googleHowSearchWorks = "https://developers.google.com/search/docs/fundamentals/how-search-works?hl=pt-br";
const googlePageIndex = "https://support.google.com/webmasters/answer/7440203?hl=pt-BR";
const googleInspection = "https://support.google.com/webmasters/answer/9012289?hl=pt-BR";
const googleSearchConsole = "https://developers.google.com/search/docs/monitor-debug/search-console-start";
const googleTechnical = "https://developers.google.com/search/docs/essentials/technical";
const googleSiteMove = "https://developers.google.com/search/docs/crawling-indexing/site-move-with-url-changes?hl=pt-BR";
const googleHostingMove = "https://developers.google.com/search/docs/crawling-indexing/site-move-no-url-changes?hl=pt-BR";

export const scenarioArticles: Record<string, Article> = {
  "site-indexado-sem-impressoes": {
    slug: "site-indexado-sem-impressoes",
    title: "Site indexado no Google, mas sem impressões: como diagnosticar antes de publicar mais conteúdo",
    metaTitle: "Site Indexado mas sem Impressões: Como Diagnosticar | AUDITSEO",
    description: "Playbook para sites indexados que quase não recebem impressões: relevância, intenção, qualidade, arquitetura, consultas, concorrência, páginas prioritárias e Search Console.",
    eyebrow: "ORGANIC ACTIVATION",
    publishedAt: "2026-09-07",
    updatedAt: "2026-09-07",
    readTime: "14 min",
    author: "Sidney Santos",
    authorUrl: "/autor/sidney-santos",
    directAnswer: "Se as páginas importantes estão indexadas mas quase não recebem impressões, o problema já não deve ser tratado apenas como indexação. O Google afirma que uma página indexada pode não aparecer quando é pouco relevante para as consultas, possui baixa qualidade ou encontra restrições de veiculação. O diagnóstico precisa avançar para intenção, arquitetura, conteúdo, competição e sinais de autoridade antes de simplesmente publicar mais URLs.",
    takeaways: [
      "Indexado significa elegível para ser servido, não garantia de impressões ou posição.",
      "Primeiro segmente o problema por página, consulta e intenção em vez de olhar apenas o tráfego total.",
      "Página sem impressões pode não possuir uma intenção clara ou pode competir com uma URL mais adequada do próprio site.",
      "Mais conteúdo não corrige automaticamente baixa relevância, arquitetura confusa ou ausência de autoridade.",
      "O primeiro marco de ativação costuma ser ganhar cobertura de consultas relevantes, não atingir um volume arbitrário de sessões.",
    ],
    blocks: [
      { type: "heading", text: "Indexação encerra uma etapa. Não encerra o diagnóstico." },
      { type: "paragraph", text: "O Google explica que, ao servir resultados, procura páginas de alta qualidade e relevância para a consulta. A própria documentação observa que o Search Console pode mostrar uma página indexada e ainda assim ela não aparecer em resultados por questões como relevância e qualidade." },
      { type: "heading", text: "1. Confirme que estamos falando de páginas realmente indexadas" },
      { type: "list", items: [
        "inspecione URLs prioritárias no Search Console",
        "confirme a canônica escolhida pelo Google",
        "verifique se não há remoções ou diretivas de veiculação inesperadas",
        "separe URLs indexadas de URLs apenas descobertas ou rastreadas",
      ] },
      { type: "heading", text: "2. Segmente impressões por página e consulta" },
      { type: "paragraph", text: "Um site pode parecer invisível no agregado enquanto algumas páginas começam a ganhar consultas long-tail. Analise páginas e queries separadamente para descobrir onde existe sinal inicial e onde a cobertura é zero." },
      { type: "list", items: [
        "páginas com zero ou quase zero impressões",
        "páginas com impressões mas CTR baixo",
        "páginas com impressões e posição distante",
        "consultas branded vs não branded",
        "consultas informacionais vs comerciais",
      ] },
      { type: "heading", text: "3. Pergunte qual intenção cada página deveria possuir" },
      { type: "paragraph", text: "Uma URL pode estar tecnicamente perfeita e ainda não possuir uma pergunta, problema ou decisão que justifique sua recuperação. Defina a intenção primária e compare o documento com o que a SERP efetivamente está resolvendo." },
      { type: "heading", text: "4. Procure sobreposição e ausência de páginas" },
      { type: "paragraph", text: "Às vezes o problema não é conteúdo fraco, mas arquitetura. Três páginas podem competir pela mesma intenção enquanto uma decisão comercial importante não possui URL própria. O trabalho é consolidar onde há duplicidade e criar apenas onde há uma lacuna real." },
      { type: "heading", text: "5. Avalie qualidade como capacidade de resolver a pergunta" },
      { type: "list", items: [
        "a resposta principal aparece cedo?",
        "há experiência, método, dados ou exemplos próprios?",
        "as afirmações importantes possuem fonte ou evidência?",
        "o texto poderia ser publicado por qualquer concorrente sem alteração?",
        "a página conecta a pergunta a uma próxima decisão do usuário?",
      ] },
      { type: "heading", text: "6. Compare o gap competitivo sem copiar a SERP" },
      { type: "paragraph", text: "Analise quais tipos de documento aparecem, quais entidades e subtópicos são cobertos, que evidências existem e quais sites recebem links e menções. O objetivo é entender o padrão de qualidade e relevância, não replicar títulos e parágrafos." },
      { type: "heading", text: "7. Fortaleça o caminho interno até as páginas prioritárias" },
      { type: "paragraph", text: "Links internos precisam ajudar usuários e crawlers a descobrir relações. Páginas estratégicas isoladas, sem contexto vindo de conteúdos e categorias relacionados, perdem parte da arquitetura que explica sua importância." },
      { type: "heading", text: "8. Defina um marco de ativação" },
      { type: "paragraph", text: "Para um site ainda sem tração, acompanhe primeiro cobertura de consultas relevantes, crescimento de impressões em páginas prioritárias e entrada de novas páginas em conjuntos de queries coerentes. Cliques e conversões vêm depois na cadeia." },
      { type: "callout", title: "Não publique para esconder o problema", text: "Se 30 páginas atuais não conquistam nenhuma consulta relevante, produzir outras 100 antes de entender a causa pode apenas ampliar o estoque de URLs sem demanda." },
    ],
    sources: [
      { label: "Google — Como a Pesquisa funciona", url: googleHowSearchWorks, note: "Explica que páginas indexadas podem não ser servidas por relevância, qualidade e regras aplicáveis." },
      { label: "Google Search Console — Indexação de páginas", url: googlePageIndex, note: "Diferencia indexação de presença garantida em resultados e orienta inspeção das páginas importantes." },
      { label: "Google Search Console — Inspeção de URL", url: googleInspection, note: "Ferramenta oficial para entender o estado de uma URL no índice e testar a versão ativa." },
    ],
    relatedServices: [["Organic Activation", "/solucoes/site-sem-tracao"], ["Intent Content Architecture", "/solucoes/conteudo-por-intencao"], ["Entity Authority", "/solucoes/autoridade-de-entidade"]],
  },

  "checklist-seo-antes-lancar-site": {
    slug: "checklist-seo-antes-lancar-site",
    title: "Checklist SEO antes de lançar um site: o que precisa estar definido antes do go-live",
    metaTitle: "Checklist SEO Antes de Lançar um Site | AUDITSEO",
    description: "Checklist pré-lançamento para arquitetura, URLs, HTTP, robots, noindex, canonical, sitemap, conteúdo, entidades, schema, analytics, Search Console e smoke pós-release.",
    eyebrow: "SEARCH FOUNDATION",
    publishedAt: "2026-09-07",
    updatedAt: "2026-09-07",
    readTime: "15 min",
    author: "Sidney Santos",
    authorUrl: "/autor/sidney-santos",
    directAnswer: "SEO de lançamento precisa ser decidido antes do go-live. Arquitetura, URLs, rastreamento, indexação, canonicals, conteúdo, dados estruturados, analytics e Search Console não deveriam ser correções da semana seguinte. O objetivo é garantir que o ambiente público nasce rastreável, indexável, semanticamente claro e mensurável — sem bloquear o site por regras herdadas do staging.",
    takeaways: [
      "Bloqueios temporários de staging, como noindex ou robots, precisam ser removidos deliberadamente no release.",
      "URLs e arquitetura devem refletir entidades, serviços e intenções antes que backlinks e histórico se acumulem.",
      "Cada página indexável precisa de status, canonical, metadata, conteúdo e links coerentes.",
      "Search Console, analytics e sitemap devem fazer parte do plano de lançamento, não de uma tarefa futura.",
      "Um smoke test pós-release deve validar o que usuários e crawlers realmente recebem em produção.",
    ],
    blocks: [
      { type: "heading", text: "1. Congele a arquitetura antes de congelar o design" },
      { type: "list", items: [
        "serviços e categorias que precisam de páginas próprias",
        "entidades centrais: empresa, pessoas, produtos, localidades e tópicos",
        "intenção primária de cada rota indexável",
        "hierarquia e links internos",
        "URLs permanentes e padrões de slug",
      ] },
      { type: "heading", text: "2. Defina o contrato HTTP" },
      { type: "list", items: [
        "200 somente para páginas reais",
        "301/308 para mudanças permanentes",
        "404 verdadeiro para URLs inexistentes",
        "5xx para indisponibilidade real, sem transformar falha de backend em soft 404",
      ] },
      { type: "heading", text: "3. Remova proteções de staging no momento correto" },
      { type: "paragraph", text: "O Google alerta explicitamente para remover bloqueios temporários de robots.txt e noindex usados durante desenvolvimento quando o novo site entra em produção. Esse é um dos erros de lançamento mais fáceis de evitar." },
      { type: "heading", text: "4. Valide canonical, robots e sitemap" },
      { type: "list", items: [
        "um canonical coerente por página indexável",
        "noindex apenas onde existe intenção deliberada de exclusão",
        "robots.txt compatível com a política pública",
        "sitemap contendo apenas URLs canônicas e prontas",
        "lastmod usado de forma consistente quando representa mudança real",
      ] },
      { type: "heading", text: "5. Garanta conteúdo visível e útil no HTML" },
      { type: "paragraph", text: "Titles e schema não substituem uma página que explique claramente problema, oferta, entidade e contexto. As páginas principais precisam nascer com conteúdo suficiente para usuários e mecanismos entenderem por que existem." },
      { type: "heading", text: "6. Estruture entidade e autoria" },
      { type: "list", items: [
        "Organization coerente com a página institucional",
        "pessoas/autores quando expertise depende delas",
        "serviços conectados à organização",
        "dados estruturados compatíveis com o conteúdo visível",
        "provas e fontes acessíveis quando claims exigem validação",
      ] },
      { type: "heading", text: "7. Configure medição antes do tráfego chegar" },
      { type: "list", items: [
        "propriedade correta no Search Console",
        "analytics e eventos de conversão",
        "UTMs e origem dos leads quando aplicável",
        "baseline das páginas e consultas prioritárias",
        "monitoramento de 404/5xx e logs quando disponível",
      ] },
      { type: "heading", text: "8. Faça smoke test em produção" },
      { type: "paragraph", text: "O ambiente real pode se comportar diferente do staging por CDN, redirects, variáveis e middleware. Após o release, teste páginas indexáveis, redirects, 404, sitemap, robots, canonical, H1, metadata e formulários críticos." },
      { type: "callout", title: "Regra de fundação", text: "É mais barato impedir dívida de busca antes do lançamento do que descobrir meses depois que URLs, templates e conteúdo nasceram sem um modelo coerente." },
    ],
    sources: [
      { label: "Google Search Central — requisitos técnicos", url: googleTechnical, note: "Base oficial para acessibilidade, HTTP e conteúdo indexável." },
      { label: "Google Search Central — começar com Search Console", url: googleSearchConsole, note: "Orientações para verificar propriedade, monitorar rastreamento, indexação e mudanças do site." },
      { label: "Google Search Central — mudanças de hospedagem", url: googleHostingMove, note: "Documenta testes de infraestrutura e remoção de bloqueios temporários antes do go-live." },
    ],
    relatedServices: [["Search Foundation", "/solucoes/projetos-comecando-do-zero"], ["SEO Migration & Risk Control", "/solucoes/migracao-risco-seo"], ["Entity Authority", "/solucoes/autoridade-de-entidade"]],
  },

  "queda-trafego-depois-redesign": {
    slug: "queda-trafego-depois-redesign",
    title: "Tráfego orgânico caiu depois do redesign: como separar migração, conteúdo e problema técnico",
    metaTitle: "Tráfego Caiu Após Redesign? Diagnóstico SEO | AUDITSEO",
    description: "Playbook para investigar queda orgânica após redesign ou migração: timeline, URLs, redirects, canonical, noindex, conteúdo, links internos, renderização, Search Console e segmentação do impacto.",
    eyebrow: "SEARCH RECOVERY",
    publishedAt: "2026-09-07",
    updatedAt: "2026-09-07",
    readTime: "15 min",
    author: "Sidney Santos",
    authorUrl: "/autor/sidney-santos",
    directAnswer: "Uma queda após redesign não prova que o design causou a perda. O redesign pode ter alterado URLs, conteúdo, links internos, renderização, canonicals, robots, templates ou infraestrutura. O diagnóstico deve construir uma timeline, segmentar onde a perda ocorreu e comparar o ambiente antigo e o novo antes de prescrever reversões ou criar conteúdo novo.",
    takeaways: [
      "Correlação temporal entre redesign e queda é um sinal de investigação, não prova automática de causa.",
      "Mudanças de URL exigem equivalência e redirects permanentes; conteúdo e links internos também precisam ser comparados.",
      "Noindex/robots de staging, canonical incorreto e redirects para destinos errados são falhas comuns de migração.",
      "A perda precisa ser segmentada por diretório, template, página e consulta.",
      "O plano de recuperação deve priorizar regressões comprovadas antes de mudanças editoriais especulativas.",
    ],
    blocks: [
      { type: "heading", text: "1. Construa a timeline antes de procurar culpados" },
      { type: "list", items: [
        "data de deploy e alterações subsequentes",
        "mudanças de domínio, URL, CMS, hosting ou CDN",
        "mudanças em templates e conteúdo",
        "alterações de tracking",
        "updates públicos do Google no mesmo período",
      ] },
      { type: "heading", text: "2. Segmente onde a queda aconteceu" },
      { type: "paragraph", text: "Compare cliques, impressões, queries, páginas e diretórios. Se apenas um template caiu, a hipótese é diferente de uma perda sitewide. Se impressões permanecem e cliques caem, o problema também difere de uma perda de cobertura." },
      { type: "heading", text: "3. Compare URLs antigas e novas" },
      { type: "list", items: [
        "URL antiga → destino correto",
        "redirect permanente sem cadeias desnecessárias",
        "equivalência de conteúdo e intenção",
        "canonical apontando para a URL final",
        "links internos atualizados para os novos endereços",
        "sitemap com URLs novas e canônicas",
      ] },
      { type: "paragraph", text: "O Google recomenda preparar um mapeamento entre URLs antigas e novas e manter redirects permanentes por longo período. Redirecionar tudo para a home ou para páginas pouco equivalentes não preserva corretamente a experiência nem o contexto." },
      { type: "heading", text: "4. Procure bloqueios herdados de staging" },
      { type: "paragraph", text: "Noindex, robots.txt restritivo, autenticação, firewall e headers podem sobreviver ao release. O Google cita bloqueios de noindex/robots entre erros comuns em mudanças de site." },
      { type: "heading", text: "5. Compare o conteúdo, não apenas o layout" },
      { type: "paragraph", text: "Redesigns frequentemente reduzem texto, removem FAQs, alteram headings, escondem links ou consolidam páginas. Compare a informação que existia antes e depois e identifique se a nova versão deixou de responder consultas que geravam demanda." },
      { type: "heading", text: "6. Audite links internos e navegação" },
      { type: "paragraph", text: "Menus simplificados e novas arquiteturas podem aumentar profundidade ou remover links contextuais para páginas importantes. O redesign pode ter mudado o grafo interno mesmo quando nenhuma URL foi alterada." },
      { type: "heading", text: "7. Valide infraestrutura e renderização" },
      { type: "list", items: [
        "5xx, timeouts e capacidade do servidor",
        "mudança de hosting/CDN",
        "conteúdo renderizado diferente para crawlers",
        "JavaScript que impede conteúdo crítico de aparecer",
        "Core Web Vitals e experiência quando houve regressão relevante",
      ] },
      { type: "heading", text: "8. Recupere regressões comprovadas primeiro" },
      { type: "paragraph", text: "Se páginas de alto valor perderam conteúdo, redirects estão errados ou links foram removidos, essas regressões têm evidência mais forte do que uma hipótese abstrata de 'o algoritmo não gostou do redesign'. Priorize o que pode ser reproduzido e validado." },
      { type: "callout", title: "Regra de recuperação", text: "Não tente recuperar um site reescrevendo tudo ao mesmo tempo. Primeiro restaure equivalência, acesso, conteúdo e sinais que foram objetivamente quebrados; depois reavalie o que continua faltando." },
    ],
    sources: [
      { label: "Google Search Central — mudanças e migrações de sites", url: googleSiteMove, note: "Guia oficial para mapeamento de URLs, redirects, sitemap, Search Console e monitoramento de migrações." },
      { label: "Google Search Central — mudança de hospedagem", url: googleHostingMove, note: "Guia para infraestrutura, Googlebot, bloqueios temporários e monitoramento após mudança de hosting/CDN." },
      { label: "Google Search Console — começar", url: googleSearchConsole, note: "Referência para monitorar tráfego, indexação e mudanças relevantes com Search Console." },
    ],
    relatedServices: [["Search Recovery", "/solucoes/recuperacao-organica"], ["SEO Migration & Risk Control", "/solucoes/migracao-risco-seo"], ["Organic Evolution Cycle", "/solucoes/evolucao-organica"]],
  },
};

export const scenarioArticleList = Object.values(scenarioArticles);
