import type { Article } from "./articles";

const googleLocalRanking = "https://support.google.com/business/answer/7091?hl=pt-BR";
const googleReviews = "https://support.google.com/business/answer/3474050?hl=pt-BR";
const googleReviewRequests = "https://support.google.com/business/answer/3474122?hl=pt-BR";
const googleCoreWebVitals = "https://developers.google.com/search/docs/appearance/core-web-vitals?hl=pt-BR";
const googlePageExperience = "https://developers.google.com/search/docs/appearance/page-experience?hl=pt-BR";

export const legacyPreservedArticles: Record<string, Article> = {
  "google-meu-negocio-guia-completo": {
    slug: "google-meu-negocio-guia-completo",
    title: "Google Business Profile em 2026: o que realmente influencia a visibilidade local",
    metaTitle: "Google Business Profile em 2026: Guia de Visibilidade Local | AUDITSEO",
    description: "Guia atualizado sobre Google Business Profile: relevância, distância, destaque, informações do perfil, avaliações e o que não pode ser prometido em SEO local.",
    eyebrow: "SEO LOCAL E ENTIDADE",
    publishedAt: "2026-01-15",
    updatedAt: "2026-09-08",
    readTime: "13 min",
    author: "Sidney Santos",
    authorUrl: "/autor/sidney-santos",
    directAnswer: "O Google Business Profile pode ampliar a presença de uma empresa em resultados locais, mas não existe configuração capaz de garantir primeira posição no Maps. O próprio Google informa que a classificação local se baseia principalmente em relevância, distância e destaque. Na prática, uma operação sólida começa por dados completos e precisos, categoria adequada, horários e localização corretos, avaliações genuínas, respostas úteis e consistência entre perfil, site e demais fontes públicas.",
    takeaways: [
      "O Google não oferece forma de pagar ou solicitar uma classificação local melhor.",
      "Relevância, distância e destaque são os três eixos que o Google documenta para resultados locais.",
      "Informações completas e precisas ajudam o mecanismo a compreender a empresa e combiná-la com pesquisas relevantes.",
      "Avaliações devem refletir experiências reais; incentivos em troca de avaliações violam as políticas do Google.",
      "SEO local não deve depender apenas do Perfil da Empresa: site, entidade, reputação e presença externa precisam ser coerentes.",
    ],
    blocks: [
      { type: "heading", text: "Primeiro: Google Meu Negócio agora é Google Business Profile" },
      { type: "paragraph", text: "O nome mudou, mas a função central continua: permitir que empresas elegíveis gerenciem como informações comerciais aparecem no Google Search e no Google Maps. Para operações locais, esse perfil é uma superfície importante da entidade — não um atalho isolado para ranking." },
      { type: "heading", text: "O que o Google realmente diz sobre ranking local" },
      { type: "paragraph", text: "Na documentação oficial, o Google afirma que os resultados locais se baseiam principalmente em relevância, distância e destaque. Isso já elimina boa parte do discurso simplista de 'otimizar o perfil e dominar o Maps'." },
      { type: "list", items: [
        "Relevância: quão bem o perfil corresponde ao que a pessoa está buscando.",
        "Distância: proximidade entre o negócio e a localização usada na pesquisa.",
        "Destaque: quão conhecida é a empresa, considerando sinais públicos como links, avaliações e outras informações disponíveis ao Google.",
      ] },
      { type: "heading", text: "1. Complete e mantenha os dados corretos" },
      { type: "paragraph", text: "O Google recomenda informações comerciais completas e precisas. Isso inclui nome, categoria, endereço ou área de atendimento quando aplicável, horários, telefone, site e atributos relevantes. Inconsistência entre perfil e site cria ambiguidade justamente onde a entidade deveria ser clara." },
      { type: "heading", text: "2. Categoria é contexto, não keyword stuffing" },
      { type: "paragraph", text: "A categoria ajuda o Google a entender o tipo de negócio. O objetivo não é transformar o nome da empresa em uma lista de palavras-chave, mas escolher categorias que representem de forma fiel a atividade real." },
      { type: "heading", text: "3. Avaliações ajudam — mas precisam ser genuínas" },
      { type: "paragraph", text: "O Google informa que avaliações positivas e respostas úteis podem ajudar a empresa a se destacar. Também proíbe incentivos, descontos ou outras recompensas em troca de avaliações, alteração de avaliações ou remoção de críticas negativas." },
      { type: "list", items: [
        "peça avaliações após experiências reais",
        "facilite o acesso ao link oficial de avaliação",
        "responda avaliações com contexto e profissionalismo",
        "não compre avaliações e não ofereça benefício em troca de feedback",
      ] },
      { type: "heading", text: "4. Fotos, vídeos e detalhes ajudam o usuário a decidir" },
      { type: "paragraph", text: "O Perfil da Empresa não existe apenas para o algoritmo. Fotos, vídeos, horários, atributos e informações atualizadas reduzem fricção na decisão de pessoas que já estão pesquisando uma solução próxima." },
      { type: "heading", text: "5. O site continua sendo parte da equação" },
      { type: "paragraph", text: "O perfil local deve apontar para uma presença controlada e coerente. Páginas de serviço, localidades reais, equipe, provas, políticas, dados estruturados e informações institucionais ajudam a reduzir contradições entre o que a empresa declara no perfil e o que o restante da web mostra." },
      { type: "heading", text: "6. Consistência de entidade importa mais que preenchimento mecânico" },
      { type: "paragraph", text: "Nome, endereço, telefone, categoria, serviços, especialistas e áreas atendidas precisam formar uma narrativa estável. Diretórios antigos, números desatualizados ou descrições contraditórias podem enfraquecer a clareza pública da entidade." },
      { type: "heading", text: "7. O que não prometer em SEO local" },
      { type: "list", items: [
        "primeira posição garantida no Maps",
        "controle sobre distância do usuário",
        "resultado local apenas por quantidade de avaliações",
        "ganho automático por publicar posts com frequência fixa",
        "vantagem por inserir palavras-chave indevidas no nome do negócio",
      ] },
      { type: "heading", text: "8. Como auditar um Perfil da Empresa" },
      { type: "list", items: [
        "verificação e propriedade do perfil",
        "nome, categoria principal e categorias secundárias",
        "endereço, área atendida e horários",
        "telefone, site e URLs de destino",
        "serviços e atributos aplicáveis",
        "qualidade e recência das avaliações",
        "respostas da empresa",
        "consistência com site, schema e fontes externas",
        "páginas locais e intenção geográfica quando realmente existem",
      ] },
      { type: "callout", title: "Princípio AUDITSEO", text: "SEO local não é 'otimizar uma ficha'. É reduzir a distância entre o que a empresa é, o que o perfil declara, o que o site comprova e o que fontes externas confirmam — respeitando a localização real do usuário e do negócio." },
    ],
    sources: [
      { label: "Google — melhorar a classificação local", url: googleLocalRanking, note: "Documentação oficial sobre relevância, distância, destaque e manutenção de informações completas e precisas." },
      { label: "Google — gerenciar avaliações", url: googleReviews, note: "Orientações oficiais para leitura e resposta a avaliações no Perfil da Empresa." },
      { label: "Google — boas práticas para receber avaliações", url: googleReviewRequests, note: "Política e boas práticas para solicitar avaliações sem incentivos ou manipulação." },
    ],
    relatedServices: [["Entity Authority", "/solucoes/autoridade-de-entidade"], ["Intent Content Architecture", "/solucoes/conteudo-por-intencao"], ["Search Foundation", "/solucoes/projetos-comecando-do-zero"]],
  },

  "core-web-vitals-guia": {
    slug: "core-web-vitals-guia",
    title: "Core Web Vitals em 2026: como medir LCP, INP e CLS sem transformar performance em mito de ranking",
    metaTitle: "Core Web Vitals 2026: LCP, INP e CLS sem Hype | AUDITSEO",
    description: "Guia técnico atualizado sobre Core Web Vitals: LCP, INP, CLS, dados de campo, Search Console, experiência de página e o papel real dessas métricas no SEO.",
    eyebrow: "SEO TÉCNICO E EXPERIÊNCIA",
    publishedAt: "2026-01-12",
    updatedAt: "2026-09-08",
    readTime: "14 min",
    author: "Sidney Santos",
    authorUrl: "/autor/sidney-santos",
    directAnswer: "Core Web Vitals medem aspectos da experiência real de carregamento, responsividade e estabilidade visual. O Google recomenda LCP de até 2,5 segundos, INP abaixo de 200 ms e CLS abaixo de 0,1 para uma boa experiência. Esses sinais fazem parte do conjunto de aspectos de experiência considerado pelos sistemas de ranking, mas atingir notas verdes não garante posições superiores. O uso correto é diagnosticar experiência e regressões, não perseguir uma pontuação perfeita como fim em si mesmo.",
    takeaways: [
      "LCP mede carregamento do maior conteúdo visível; a referência de boa experiência é até 2,5 s.",
      "INP mede capacidade de resposta; a referência de boa experiência é abaixo de 200 ms.",
      "CLS mede estabilidade visual; a referência de boa experiência é abaixo de 0,1.",
      "O Google recomenda bons Core Web Vitals, mas afirma que boas notas não garantem ranking no topo.",
      "Dados de campo e regressões por template são mais úteis para decisão do que perseguir Lighthouse 100 em todas as páginas.",
    ],
    blocks: [
      { type: "heading", text: "O que Core Web Vitals realmente medem" },
      { type: "paragraph", text: "Core Web Vitals são métricas de experiência real do usuário relacionadas a carregamento, capacidade de resposta e estabilidade visual. Elas ajudam a transformar 'o site parece lento' em sinais observáveis que podem ser monitorados por página ou grupo de páginas." },
      { type: "heading", text: "As três métricas atuais" },
      { type: "list", items: [
        "LCP (Largest Contentful Paint): desempenho de carregamento; boa experiência até 2,5 s.",
        "INP (Interaction to Next Paint): capacidade de resposta; boa experiência abaixo de 200 ms.",
        "CLS (Cumulative Layout Shift): estabilidade visual; boa experiência abaixo de 0,1.",
      ] },
      { type: "heading", text: "Core Web Vitals são fator de ranking?" },
      { type: "paragraph", text: "O Google afirma que Core Web Vitals são usados por seus sistemas de ranking dentro de um conjunto mais amplo de sinais relacionados à experiência. A própria documentação também alerta que obter bons resultados nesses relatórios não garante que uma página aparecerá no topo. Relevância, utilidade e qualidade do conteúdo continuam fundamentais." },
      { type: "heading", text: "1. LCP: investigue o caminho crítico" },
      { type: "paragraph", text: "LCP tende a piorar quando o maior elemento visível depende de resposta lenta do servidor, recurso pesado, CSS/JS bloqueante, fonte atrasada ou descoberta tardia da imagem principal. O diagnóstico deve identificar o elemento LCP real em cada template antes de aplicar otimizações genéricas." },
      { type: "heading", text: "2. INP: procure trabalho excessivo na main thread" },
      { type: "paragraph", text: "INP representa a resposta visual após interações. JavaScript pesado, long tasks, hidratação custosa e handlers complexos podem prejudicar a capacidade de resposta mesmo quando o carregamento inicial parece rápido." },
      { type: "heading", text: "3. CLS: reserve espaço antes do conteúdo chegar" },
      { type: "paragraph", text: "Mudanças inesperadas de layout normalmente surgem de imagens sem dimensões, embeds, anúncios, banners inseridos acima do conteúdo ou trocas de fonte que alteram medidas. Estabilidade depende de reservar espaço e evitar alterações visuais imprevisíveis." },
      { type: "heading", text: "4. Dados de campo e laboratório respondem perguntas diferentes" },
      { type: "paragraph", text: "Dados de campo mostram como usuários reais experimentam páginas ao longo do tempo e são a base dos relatórios de Core Web Vitals. Testes de laboratório são valiosos para reproduzir problemas e investigar causas, mas não substituem a leitura do comportamento real quando ela está disponível." },
      { type: "heading", text: "5. Audite por template, não apenas por URL isolada" },
      { type: "list", items: [
        "home e landing pages",
        "artigos e documentos longos",
        "páginas de serviço",
        "templates dinâmicos",
        "páginas com vídeos, mapas ou embeds",
        "fluxos com formulários e interação intensa",
      ] },
      { type: "paragraph", text: "Um problema repetido em um componente compartilhado pode afetar centenas de URLs. Por isso, a unidade de correção muitas vezes é o template ou componente, não a página individual." },
      { type: "heading", text: "6. Não sacrifique produto para buscar score perfeito" },
      { type: "paragraph", text: "O próprio Google recomenda bons Core Web Vitals para Search e experiência, mas também alerta que perseguir uma pontuação perfeita apenas por SEO pode não ser o melhor uso de recursos. A decisão precisa considerar impacto no usuário, escala do problema e custo da correção." },
      { type: "heading", text: "7. Como transformar CWV em um processo de engenharia" },
      { type: "list", items: [
        "baseline de campo por grupo de páginas",
        "identificação do elemento ou interação responsável",
        "hipótese técnica",
        "correção em ambiente de teste",
        "validação de laboratório para regressão",
        "monitoramento após release",
        "comparação com dados de campo quando a janela permitir",
      ] },
      { type: "heading", text: "8. Onde Core Web Vitals entram numa auditoria SEO" },
      { type: "paragraph", text: "Performance deve entrar como uma camada do diagnóstico técnico, junto com HTTP, renderização, indexação, canonicals, arquitetura, conteúdo e comportamento. Uma nota ruim pode revelar fricção real; uma nota verde não prova que a página é relevante, útil ou competitiva." },
      { type: "callout", title: "Princípio AUDITSEO", text: "Core Web Vitals são sinais de experiência a serem diagnosticados e monitorados. Não são um placar de autoridade e não devem substituir a investigação sobre intenção, conteúdo, recuperação e conversão." },
    ],
    sources: [
      { label: "Google Search Central — Core Web Vitals", url: googleCoreWebVitals, note: "Definições atuais de LCP, INP e CLS e recomendações de boa experiência." },
      { label: "Google Search Central — Page Experience", url: googlePageExperience, note: "Contexto oficial sobre uso de sinais de experiência e ausência de garantia de ranking por boas métricas isoladas." },
    ],
    relatedServices: [["Search Foundation", "/solucoes/projetos-comecando-do-zero"], ["Search Recovery", "/solucoes/recuperacao-organica"], ["SEO Migration & Risk Control", "/solucoes/migracao-risco-seo"]],
  },
};

export const legacyPreservedArticleList = Object.values(legacyPreservedArticles);
