import type { Article } from "./articles";

const googleHelpful = "https://developers.google.com/search/docs/fundamentals/creating-helpful-content";
const googleCoreUpdates = "https://developers.google.com/search/docs/appearance/core-updates";
const googleTrafficDrops = "https://developers.google.com/search/docs/monitor-debug/debugging-search-traffic-drops";
const googleSearchConsole = "https://developers.google.com/search/docs/monitor-debug/search-console-start";

export const growthOpsArticles: Record<string, Article> = {
  "conteudo-sem-trafego-atualizar-consolidar-remover": {
    slug: "conteudo-sem-trafego-atualizar-consolidar-remover",
    title: "Conteúdo sem tráfego: atualizar, consolidar ou remover? Como decidir sem fazer content pruning no escuro",
    metaTitle: "Conteúdo sem Tráfego: Atualizar, Consolidar ou Remover? | AUDITSEO",
    description: "Framework para decidir o que fazer com artigos sem tráfego: intenção, impressões, links, conversão, sobreposição, qualidade, atualização e remoção sem content pruning automático.",
    eyebrow: "INTENT CONTENT ARCHITECTURE",
    publishedAt: "2026-09-07",
    updatedAt: "2026-09-07",
    readTime: "14 min",
    author: "Sidney Santos",
    authorUrl: "/autor/sidney-santos",
    directAnswer: "Conteúdo sem tráfego não deve ser removido automaticamente. Primeiro determine se a página possui uma intenção útil, recebe impressões, links, conversões assistidas, tráfego de outros canais, valor de referência ou sobreposição com outra URL. Atualize quando a intenção continua válida mas o documento perdeu qualidade ou precisão; consolide quando várias páginas disputam a mesma decisão; remova ou redirecione quando não existe mais propósito útil e há um destino equivalente. O Google desaconselha adicionar ou remover grandes volumes apenas para fazer o site parecer 'fresco'.",
    takeaways: [
      "Zero cliques não significa automaticamente zero valor.",
      "Content pruning por tráfego isolado pode apagar páginas com links, utilidade, branded demand ou função de jornada.",
      "Atualizar faz sentido quando a intenção continua relevante e o conteúdo pode ficar substancialmente melhor.",
      "Consolidar é preferível quando duas ou mais URLs respondem essencialmente à mesma decisão.",
      "Remover grandes volumes apenas para sinalizar frescor não é uma recomendação do Google.",
    ],
    blocks: [
      { type: "heading", text: "O erro: usar tráfego como único critério de existência" },
      { type: "paragraph", text: "Uma página pode ter poucos cliques e ainda apoiar conversão, responder branded queries, receber links, explicar uma entidade ou funcionar como referência interna. A decisão precisa considerar função, não apenas sessões." },
      { type: "heading", text: "1. Classifique a intenção antes da performance" },
      { type: "list", items: [
        "a página responde uma pergunta ou decisão que ainda existe?",
        "a intenção pertence ao foco real da empresa?",
        "há outra URL mais adequada para responder à mesma necessidade?",
        "a página sustenta uma oferta, entidade ou etapa da jornada?",
      ] },
      { type: "heading", text: "2. Separe zero impressão de baixa conversão" },
      { type: "paragraph", text: "Zero impressões sugere um problema diferente de uma página com muitas impressões e poucos cliques. Uma pode não ser recuperada para intenção relevante; a outra pode ter snippet, posição ou alinhamento de expectativa fracos." },
      { type: "heading", text: "3. Atualize quando a intenção é boa e o documento ficou para trás" },
      { type: "list", items: [
        "informação desatualizada ou imprecisa",
        "resposta superficial comparada ao que o usuário precisa hoje",
        "ausência de experiência, exemplos, fontes ou metodologia",
        "produto ou serviço mudou e a página não acompanhou",
        "consultas reais mostram subtópicos que o documento ainda não cobre",
      ] },
      { type: "paragraph", text: "O Google recomenda conteúdo útil, original e confiável e alerta contra simplesmente mudar datas para parecer fresco sem alteração substancial." },
      { type: "heading", text: "4. Consolide quando existe sobreposição real" },
      { type: "paragraph", text: "Se duas páginas tentam resolver a mesma intenção e nenhuma possui papel distinto, uma página canônica mais completa pode ser mais clara para usuários e para a arquitetura interna. Consolidação precisa preservar partes úteis, links e redirecionar URLs antigas quando apropriado." },
      { type: "heading", text: "5. Remova quando o propósito deixou de existir" },
      { type: "list", items: [
        "tema fora do foco atual sem valor residual",
        "conteúdo obsoleto que não pode ser atualizado de forma útil",
        "página criada exclusivamente para capturar tráfego sem servir ao público real",
        "duplicação sem justificativa e com destino canônico equivalente",
      ] },
      { type: "paragraph", text: "O Google afirma que remover conteúdo que foi criado para mecanismos em vez de pessoas pode ser útil, mas também diz que adicionar ou remover muitos conteúdos apenas para fazer o site parecer fresco não ajuda por si só. Contexto é essencial." },
      { type: "heading", text: "6. Não esqueça sinais fora do tráfego orgânico" },
      { type: "list", items: [
        "backlinks e referências externas",
        "conversões assistidas",
        "tráfego direto, social, e-mail ou referral",
        "uso por equipe comercial ou suporte",
        "relevância para entidade, documentação ou compliance",
      ] },
      { type: "heading", text: "7. Registre uma decisão por ativo" },
      { type: "paragraph", text: "Um inventário editorial útil termina com estado e justificativa: manter, atualizar, consolidar, redirecionar, remover ou medir por mais tempo. Isso transforma content pruning em governança editorial." },
      { type: "callout", title: "Princípio AUDITSEO", text: "Não pergunte 'essa página tem tráfego?'. Pergunte 'qual função ela possui, quais evidências mostram que cumpre essa função e existe outra URL que deveria cumpri-la melhor?'" },
    ],
    sources: [
      { label: "Google — conteúdo útil e people-first", url: googleHelpful, note: "Perguntas oficiais sobre originalidade, utilidade, experiência e alertas contra produção/remoção focada apenas em rankings ou frescor." },
      { label: "Google — core updates", url: googleCoreUpdates, note: "Contexto oficial sobre melhoria de conteúdo, remoção de conteúdo criado para buscadores e ausência de garantia de recuperação." },
      { label: "Google — Search Console", url: googleSearchConsole, note: "Fonte para análise de páginas, queries, impressões e cliques antes de decidir sobre ativos." },
    ],
    relatedServices: [["Intent Content Architecture", "/solucoes/conteudo-por-intencao"], ["Organic Evolution Cycle", "/solucoes/evolucao-organica"], ["Organic Activation", "/solucoes/site-sem-tracao"]],
  },

  "trafego-organico-estagnado-proxima-oportunidade": {
    slug: "trafego-organico-estagnado-proxima-oportunidade",
    title: "Tráfego orgânico estagnou: como encontrar a próxima oportunidade sem voltar ao checklist mensal",
    metaTitle: "Tráfego Orgânico Estagnado: Como Encontrar Crescimento | AUDITSEO",
    description: "Framework para operações SEO maduras encontrarem próximas oportunidades: queries, páginas, decay, CTR, novas intenções, demanda, concorrência, Search AI e learning loop.",
    eyebrow: "ORGANIC EVOLUTION CYCLE",
    publishedAt: "2026-09-07",
    updatedAt: "2026-09-07",
    readTime: "15 min",
    author: "Sidney Santos",
    authorUrl: "/autor/sidney-santos",
    directAnswer: "Quando o tráfego orgânico estabiliza, o próximo passo não é necessariamente publicar mais. Compare períodos e segmentos no Search Console, separe demanda externa de perda competitiva, identifique páginas com decay, queries em ascensão, CTR desperdiçado, intenções adjacentes e ofertas ainda sem cobertura. Depois transforme cada oportunidade em hipótese com baseline, ação e critério de validação. Crescimento maduro depende de ciclos de aprendizado, não de repetir o mesmo checklist.",
    takeaways: [
      "Estagnação não significa automaticamente problema técnico ou penalização.",
      "Demanda pode mudar por sazonalidade e comportamento do mercado; compare Search Console com sinais externos.",
      "Páginas em decay podem ter retorno maior que a criação de novas URLs.",
      "Queries com posição intermediária e relevância comercial podem revelar expansão de conteúdo e arquitetura.",
      "Cada ciclo precisa registrar hipótese, ação e resultado para parar tarefas que não produzem movimento.",
    ],
    blocks: [
      { type: "heading", text: "Primeiro: estagnação é diferente de queda" },
      { type: "paragraph", text: "Uma curva estável pode significar que a operação atingiu o limite do conjunto atual de páginas e intenções, que a demanda não cresceu, que concorrentes avançaram ou que oportunidades novas ainda não foram exploradas. O diagnóstico é diferente de uma perda abrupta." },
      { type: "heading", text: "1. Compare períodos e segmentos" },
      { type: "paragraph", text: "O Google recomenda usar comparações no Performance report e olhar queries, páginas, países, dispositivos e tipos de pesquisa. Para operações maduras, o agregado esconde onde ainda existe movimento." },
      { type: "list", items: [
        "consultas que crescem enquanto o total fica estável",
        "páginas que perderam cobertura gradualmente",
        "clusters que ganham impressões mas não cliques",
        "branded vs não branded",
        "novas ofertas sem páginas ou conteúdo de suporte",
      ] },
      { type: "heading", text: "2. Separe perda de demanda de perda competitiva" },
      { type: "paragraph", text: "O Google cita sazonalidade e mudanças de interesse como causas possíveis de variação. Uma query pode cair para todo o mercado. Se a demanda permanece e sua participação encolhe, a hipótese competitiva ganha força." },
      { type: "heading", text: "3. Procure content decay antes de criar" },
      { type: "paragraph", text: "Páginas antigas podem perder precisão, profundidade, diferenciação e links internos. Atualizar um ativo já conhecido pelo mercado pode ser mais eficiente que abrir uma URL nova, desde que a intenção continue válida." },
      { type: "heading", text: "4. Minere queries próximas de oportunidade" },
      { type: "list", items: [
        "queries relevantes com impressões crescentes",
        "consultas em que a página aparece mas não responde diretamente",
        "termos comerciais sem página dedicada",
        "perguntas de comparação e validação próximas da compra",
        "variações locais ou setoriais quando realmente mudam a decisão",
      ] },
      { type: "heading", text: "5. Revise CTR sem transformar title em caça-clique" },
      { type: "paragraph", text: "Se impressões permanecem e cliques caem, o Google sugere investigar title/snippet e mudanças na apresentação dos resultados. O objetivo é representar melhor a página e a intenção, não exagerar a promessa." },
      { type: "heading", text: "6. Observe novas interfaces sem abandonar o orgânico clássico" },
      { type: "paragraph", text: "Search AI pode entrar no ciclo como outra camada de descoberta. Meça prompts relacionados a intenções importantes, fontes citadas e precisão de entidade, mas mantenha essa leitura conectada a páginas, demanda e conversão do negócio." },
      { type: "heading", text: "7. Transforme oportunidade em hipótese" },
      { type: "list", items: [
        "baseline: qual sinal observamos agora?",
        "hipótese: por que acreditamos que existe oportunidade?",
        "ação: qual mudança testaremos?",
        "métrica: o que deveria se mover se estivermos certos?",
        "janela: quando faz sentido reavaliar?",
        "decisão: manter, expandir, interromper ou formular nova hipótese",
      ] },
      { type: "heading", text: "8. Pare tarefas que sobrevivem apenas por hábito" },
      { type: "paragraph", text: "Relatórios e tarefas recorrentes precisam justificar sua permanência. Se uma atividade não resolve um problema atual, não produz aprendizado e não protege um ativo, ela compete por recursos com oportunidades mais fortes." },
      { type: "callout", title: "Learning Loop", text: "A maturidade de uma operação orgânica aparece quando ela consegue dizer não apenas o que fez, mas o que aprendeu — e como esse aprendizado mudou a próxima prioridade." },
    ],
    sources: [
      { label: "Google — Debugging Search traffic drops", url: googleTrafficDrops, note: "Orientações atuais para comparar períodos, segmentar páginas/queries e separar causas técnicas, algorítmicas e de demanda." },
      { label: "Google — Search Console", url: googleSearchConsole, note: "Base para análise contínua de páginas, queries, impressões, cliques e indexação." },
      { label: "Google — conteúdo útil e people-first", url: googleHelpful, note: "Critérios de qualidade para decidir quando conteúdo precisa de melhoria substancial em vez de expansão por volume." },
    ],
    relatedServices: [["Organic Evolution Cycle", "/solucoes/evolucao-organica"], ["Intent Content Architecture", "/solucoes/conteudo-por-intencao"], ["Search Recovery", "/solucoes/recuperacao-organica"]],
  },
};

export const growthOpsArticleList = Object.values(growthOpsArticles);
