import type { Article } from "./articles";

const googleHireSeo = "https://developers.google.com/search/docs/fundamentals/do-i-need-seo?hl=pt-BR";
const googleThirdParty = "https://developers.google.com/search/docs/fundamentals/third-party-seo?hl=pt-br";
const googleCrawling = "https://developers.google.com/search/docs/crawling-indexing";
const googleTechnical = "https://developers.google.com/search/docs/essentials/technical";
const googleHelpful = "https://developers.google.com/search/docs/fundamentals/creating-helpful-content";

export const buyerOpsArticles: Record<string, Article> = {
  "o-que-consultoria-seo-deve-entregar": {
    slug: "o-que-consultoria-seo-deve-entregar",
    title: "O que uma consultoria de SEO deve entregar? O que muda conforme o problema",
    metaTitle: "O que uma Consultoria de SEO Deve Entregar? | AUDITSEO",
    description: "Entenda quais entregáveis fazem sentido em consultoria SEO, por que não existe checklist universal e como diagnóstico, roadmap, documentação, implementação e validação devem se conectar.",
    eyebrow: "DECISÃO DE CONTRATAÇÃO",
    publishedAt: "2026-09-07",
    updatedAt: "2026-09-07",
    readTime: "13 min",
    author: "Sidney Santos",
    authorUrl: "/autor/sidney-santos",
    directAnswer: "Uma consultoria de SEO deve entregar clareza sobre o problema, evidências que sustentam o diagnóstico, prioridades, recomendações explicadas, responsáveis, critérios de validação e acompanhamento dos resultados. O formato muda conforme o cenário: um site novo precisa de arquitetura e requisitos; uma queda precisa de investigação; uma migração precisa de mapa de risco; um programa contínuo precisa de backlog e aprendizado. Um pacote fixo de entregáveis não substitui diagnóstico.",
    takeaways: [
      "O principal entregável de uma consultoria não é um PDF: é uma decisão tecnicamente defensável.",
      "Auditoria, roadmap e implementação precisam estar conectados ao problema original.",
      "O Google recomenda transparência sobre mudanças, lógica das recomendações e estimativas realistas de melhoria e trabalho.",
      "Entregáveis devem variar por cenário; repetir o mesmo checklist para todos os clientes é um sinal de baixa personalização.",
      "Mensuração precisa responder se o gargalo original mudou, não apenas se tarefas foram concluídas.",
    ],
    blocks: [
      { type: "heading", text: "O erro de comprar SEO pela quantidade de entregáveis" },
      { type: "paragraph", text: "Propostas costumam competir por volume: auditoria, palavras-chave, relatórios, links, artigos, schema, dashboards. O problema é que uma lista longa pode parecer completa e ainda não dizer qual causa será atacada." },
      { type: "paragraph", text: "O Google recomenda avaliar se o profissional entende o negócio, explica o raciocínio, comunica as mudanças e oferece estimativas realistas. Isso coloca a qualidade da decisão acima da quantidade de itens em um pacote." },
      { type: "heading", text: "1. Diagnóstico com evidência" },
      { type: "list", items: [
        "baseline de tráfego, consultas, páginas e conversões relevantes",
        "estado de rastreamento, indexação e renderização quando aplicável",
        "mapa de intenção e páginas prioritárias",
        "hipóteses competitivas e editoriais",
        "separação entre fato observado, hipótese e recomendação",
      ] },
      { type: "heading", text: "2. Priorização, não apenas lista de problemas" },
      { type: "paragraph", text: "Uma consultoria útil precisa dizer o que fazer primeiro, o que pode esperar e o que não deve ser feito. Impacto, risco, esforço, dependências e proximidade comercial devem entrar na priorização." },
      { type: "heading", text: "3. Recomendação explicada" },
      { type: "paragraph", text: "Toda mudança relevante precisa de racional: qual problema resolve, qual evidência a sustenta, quem implementa, qual risco existe e como validar. Isso vale para redirects, canonicals, páginas novas, consolidação de conteúdo, schema, arquitetura e ações de autoridade." },
      { type: "heading", text: "4. Entregáveis variam pelo cenário" },
      { type: "list", items: [
        "site novo: arquitetura, requisitos de indexação, templates, entidades, medição e QA",
        "site sem tração: diagnóstico de cobertura, intenção, qualidade, autoridade e conversão",
        "queda orgânica: segmentação do impacto, timeline, hipóteses causais e plano de recuperação",
        "migração: inventário, equivalência de URLs, redirects, smoke e monitoramento",
        "Search AI: prompt baseline, fontes, elegibilidade, citabilidade e Entity Accuracy",
        "operação madura: opportunity backlog, decay, prioridades e Learning Loop",
      ] },
      { type: "heading", text: "5. Implementação ou governança da implementação" },
      { type: "paragraph", text: "Se a consultoria não implementa diretamente, ela precisa deixar requisitos suficientemente claros para desenvolvimento, conteúdo, PR ou analytics. Um backlog sem dono e sem critério de aceite não é execução." },
      { type: "heading", text: "6. Validação pós-implementação" },
      { type: "paragraph", text: "Mudança publicada não significa mudança correta. A consultoria deve validar status, renderização, canonical, links, páginas, analytics e sinais esperados quando relevantes ao escopo." },
      { type: "heading", text: "7. Relatório de aprendizado" },
      { type: "paragraph", text: "O acompanhamento precisa registrar o que mudou, o que não mudou, quais hipóteses perderam força e quais prioridades surgiram. Relatório mensal que apenas repete rankings e sessões não substitui um ciclo de decisão." },
      { type: "callout", title: "Critério AUDITSEO", text: "Um bom entregável permite que outra pessoa entenda o diagnóstico, a decisão, a implementação e o critério de validação sem depender da memória de uma reunião." },
    ],
    sources: [
      { label: "Google Search Central — Você precisa de SEO?", url: googleHireSeo, note: "O Google recomenda avaliar transparência, lógica das mudanças, referências, interesse pelo negócio e estimativas realistas." },
      { label: "Google — serviços e conselhos de terceiros", url: googleThirdParty, note: "Orientação para validar recomendações de terceiros contra documentação oficial e desconfiar de claims sem base." },
    ],
    relatedServices: [["Consultoria SEO", "/consultoria-seo"], ["Auditoria SEO", "/auditoria-seo"], ["Consultoria SEO contínua", "/solucoes/evolucao-organica"]],
  },

  "auditoria-seo-o-que-deve-conter": {
    slug: "auditoria-seo-o-que-deve-conter",
    title: "Auditoria SEO: o que deve conter para virar decisão — e não apenas uma lista de erros",
    metaTitle: "Auditoria SEO: O que Deve Conter? Checklist com Prioridade | AUDITSEO",
    description: "Veja o que uma auditoria SEO útil deve analisar: crawl, indexação, arquitetura, conteúdo, intenção, autoridade, dados, riscos, priorização, roadmap e validação.",
    eyebrow: "AUDITORIA SEO",
    publishedAt: "2026-09-07",
    updatedAt: "2026-09-07",
    readTime: "15 min",
    author: "Sidney Santos",
    authorUrl: "/autor/sidney-santos",
    directAnswer: "Uma auditoria SEO útil deve conectar evidências técnicas, conteúdo, intenção, autoridade e dados de performance a decisões priorizadas. Ela precisa explicar o que foi observado, por que importa, qual hipótese existe, qual ação é recomendada, quem depende dela e como validar o resultado. Exportar erros de um crawler ou score de ferramenta não é suficiente.",
    takeaways: [
      "Crawler é fonte de evidência, não diagnóstico completo.",
      "A auditoria precisa considerar Search Console, analytics e contexto de negócio sempre que disponíveis.",
      "HTTP, crawl, indexação, canonical, links e renderização formam a fundação técnica.",
      "Conteúdo e intenção precisam ser avaliados junto com arquitetura e entidades.",
      "O resultado final deve ser um roadmap priorizado com risco, esforço, impacto e validação.",
    ],
    blocks: [
      { type: "heading", text: "Uma auditoria não deve começar pelo score da ferramenta" },
      { type: "paragraph", text: "Ferramentas conseguem detectar padrões úteis, mas o próprio Google lembra que ferramentas de terceiros não possuem acesso aos dados internos de ranking e não são endossadas pela Pesquisa Google. A auditoria precisa interpretar evidências, não terceirizar decisão para um score." },
      { type: "heading", text: "1. Baseline e contexto" },
      { type: "list", items: [
        "objetivo comercial e páginas que sustentam receita",
        "consultas e segmentos prioritários",
        "histórico de tráfego, impressões, cliques e conversões",
        "mudanças recentes de CMS, domínio, templates, conteúdo ou tracking",
        "mercados, localidades, produtos e concorrentes relevantes",
      ] },
      { type: "heading", text: "2. Crawl e resposta do servidor" },
      { type: "paragraph", text: "Status HTTP, redirects, cadeias, 404, 5xx, robots, renderização e disponibilidade precisam ser auditados porque páginas precisam funcionar antes de qualquer discussão de relevância." },
      { type: "heading", text: "3. Indexação e canonicalização" },
      { type: "list", items: [
        "URLs indexáveis vs noindex",
        "canonical declarado vs sinais conflitantes",
        "sitemaps e URLs submetidas",
        "duplicação e páginas pouco distintas",
        "URLs válidas que não entram no índice esperado",
      ] },
      { type: "heading", text: "4. Arquitetura e links internos" },
      { type: "paragraph", text: "A auditoria deve verificar se páginas prioritárias são encontráveis, recebem contexto interno e ocupam uma posição coerente na arquitetura. Profundidade e links importam quando ajudam usuários e crawlers a descobrir e compreender relações." },
      { type: "heading", text: "5. Intenção, conteúdo e sobreposição" },
      { type: "list", items: [
        "qual intenção cada URL deve possuir",
        "lacunas de páginas para decisões importantes",
        "canibalização real vs sobreposição legítima",
        "conteúdo commodity, desatualizado ou sem evidência",
        "páginas comerciais sem sustentação temática",
      ] },
      { type: "heading", text: "6. Entidade, autoria e confiança" },
      { type: "paragraph", text: "Especialistas, organização, serviços, provas, fontes externas e structured data coerente podem participar do diagnóstico quando clareza e confiança são relevantes. Schema não deve ser auditado isoladamente do conteúdo que representa." },
      { type: "heading", text: "7. Search AI quando fizer parte do problema" },
      { type: "paragraph", text: "Se a empresa quer medir presença em IA, a auditoria deve incluir elegibilidade de crawlers documentados, prompts congelados, fontes observadas, menções, citações e precisão da entidade — sem inventar um score universal." },
      { type: "heading", text: "8. Priorização e roadmap" },
      { type: "paragraph", text: "O relatório final precisa ordenar ações. Uma forma defensável é registrar impacto esperado, evidência, esforço, risco, dependências, responsável e critério de aceite. Sem priorização, uma auditoria grande pode reduzir velocidade em vez de aumentá-la." },
      { type: "heading", text: "9. O que deve acompanhar cada achado" },
      { type: "list", items: [
        "evidência ou exemplo reproduzível",
        "escopo afetado",
        "impacto potencial e nível de confiança",
        "recomendação",
        "dependências e risco",
        "responsável sugerido",
        "como testar se foi corrigido",
      ] },
      { type: "callout", title: "Diferença essencial", text: "Crawl report diz o que uma ferramenta encontrou. Auditoria explica o que isso significa para o negócio, o que fazer primeiro e como saber se a decisão funcionou." },
    ],
    sources: [
      { label: "Google — Você precisa de SEO?", url: googleHireSeo, note: "O Google recomenda auditorias com estimativas realistas de melhoria e trabalho e alerta contra garantias de primeira posição." },
      { label: "Google — crawling e indexing", url: googleCrawling, note: "Base oficial para rastreamento, indexação, robots, links, sitemaps e mudanças de site." },
      { label: "Google — requisitos técnicos", url: googleTechnical, note: "Documenta requisitos básicos como HTTP 200 e conteúdo indexável." },
      { label: "Google — conteúdo útil", url: googleHelpful, note: "Referência para qualidade, autoria, utilidade e valor editorial." },
      { label: "Google — orientações sobre terceiros", url: googleThirdParty, note: "Alerta sobre extrapolações de ferramentas e conselhos de SEO de terceiros." },
    ],
    relatedServices: [["Auditoria SEO", "/auditoria-seo"], ["Consultoria SEO", "/consultoria-seo"], ["Recuperação de tráfego orgânico", "/solucoes/recuperacao-organica"]],
  },

  "auditoria-seo-aplicada-auditseo": {
    slug: "auditoria-seo-aplicada-auditseo",
    title: "Auditoria SEO aplicada: o que encontramos na própria AUDITSEO antes de corrigir",
    metaTitle: "Auditoria SEO Aplicada: Case AUDITSEO com GSC | AUDITSEO",
    description: "Veja uma auditoria SEO aplicada na própria AUDITSEO: baseline no Search Console, canibalização, arquitetura comercial, CTR, entidade, redirects, acessibilidade e critérios de validação.",
    eyebrow: "ESTUDO APLICADO · 01/10/2026",
    publishedAt: "2026-10-01",
    updatedAt: "2026-10-01",
    readTime: "12 min",
    author: "Sidney Santos",
    authorUrl: "/autor/sidney-santos",
    directAnswer: "Em 1º de outubro de 2026, a AUDITSEO consolidou auditoria técnica e Google Search Console antes de iniciar uma nova rodada de correções no próprio domínio. A base técnica estava saudável, mas o site tinha intenções comerciais mal distribuídas, canibalização para 'auditoria de seo', páginas em boas posições com CTR zero, lacunas de entidade/prova e inconsistências de conversão. O trabalho foi tratado como diagnóstico: registrar baseline, proteger ativos, definir um proprietário por intenção, implementar em branch e validar antes do merge.",
    takeaways: [
      "A propriedade verificada usada no checkpoint foi https://www.auditseo.com.br/.",
      "O período finalizado de 01/09/2026 a 28/09/2026 registrou 199 impressões, 2 cliques, CTR de 1,01% e posição média 24,58.",
      "A query 'auditoria de seo' aparecia dividida entre Home e artigo editorial, sem landing page comercial dedicada.",
      "Páginas entre posições 3 e 11 foram protegidas contra reescrita indiscriminada; title/meta só mudaram quando havia evidência de intenção no GSC.",
      "O trabalho criou /auditoria-seo e /consultoria-seo sem remover os artigos existentes.",
      "Este é um estudo de implementação e mensuração em andamento, não uma prova de causalidade ou promessa de ranking.",
    ],
    blocks: [
      { type: "heading", text: "1. O que foi congelado antes da correção" },
      { type: "paragraph", text: "Antes de alterar títulos, URLs ou arquitetura, registramos o desempenho da propriedade verificada no Search Console e criamos um inventário de páginas protegidas. O objetivo era evitar que uma correção apagasse um ativo que já começava a ganhar posição." },
      { type: "list", items: [
        "01/09/2026 a 28/09/2026: 199 impressões",
        "2 cliques",
        "CTR de 1,01%",
        "posição média 24,58",
        "período comparável anterior: 264 impressões, 2 cliques, CTR 0,76% e posição média 57,00",
      ] },
      { type: "paragraph", text: "A melhora de posição média não foi tratada como sucesso isolado: as impressões caíram e os cliques ficaram estáveis. Métricas precisam ser lidas juntas." },

      { type: "heading", text: "2. A arquitetura explicava o método melhor do que o serviço" },
      { type: "paragraph", text: "A Home e as soluções explicavam Search Intelligence com profundidade, mas parte da nomenclatura exigia que o comprador traduzisse nomes proprietários para categorias conhecidas. O problema não era abandonar o método; era inverter a hierarquia: linguagem de compra primeiro, assinatura proprietária depois." },
      { type: "paragraph", text: "Por isso a nova arquitetura mantém Search Intelligence e S.I.G.N.A.L. como diferenciação, mas torna Consultoria SEO, Auditoria SEO, Recuperação de Tráfego, Migração SEO e outras categorias explícitas." },

      { type: "heading", text: "3. Canibalização: 'auditoria de seo' não tinha um proprietário comercial" },
      { type: "paragraph", text: "No GSC, 'auditoria de seo' aparecia na Home e no artigo 'Auditoria SEO: o que deve conter'. O artigo é informacional; a Home é uma porta de entrada de marca/categoria. Nenhum dos dois deveria carregar sozinho a intenção de contratação." },
      { type: "paragraph", text: "A decisão foi adicionar /auditoria-seo como destino transacional e fazer Home e artigo apoiarem essa página por links e papéis de intenção diferentes. O artigo não foi apagado nem redirecionado." },

      { type: "heading", text: "4. Consultoria SEO também precisava de um destino próprio" },
      { type: "paragraph", text: "Conteúdos sobre como escolher consultoria ou o que uma consultoria deve entregar já existiam. Eles ajudam a decisão, mas não substituem uma página que explique o modelo de atuação, responsabilidades, cadência, governança, QA, mensuração e limites." },
      { type: "paragraph", text: "A nova /consultoria-seo assume a intenção comercial genérica; os artigos continuam educando e passam a direcionar a jornada para o serviço quando a leitura chega à etapa de contratação." },

      { type: "heading", text: "5. CTR zero não virou autorização para reescrever tudo" },
      { type: "paragraph", text: "Várias páginas estavam entre posições 3 e 11 com impressões e nenhum clique. Em vez de trocar títulos em massa, revisamos relação query → página. Só duas receberam ajuste inicial com evidência direta de intenção: o artigo sobre site indexado sem impressões e o benchmark sobre custo de consultoria SEO/GEO." },
      { type: "callout", title: "Regra de mudança", text: "Página bem posicionada só é reescrita quando existe evidência de desalinhamento, conteúdo factual desatualizado, conflito de intenção ou snippet claramente incompatível com a query observada." },

      { type: "heading", text: "6. Entidade e prova: o que podíamos afirmar e o que não podíamos" },
      { type: "paragraph", text: "Criamos uma página institucional separada do fundador, reforçamos Organization/Person schema, ligamos autoria, método, estudos e case e mantivemos sameAs apenas onde havia referência externa verificada. Não adicionamos perfis ou depoimentos inexistentes apenas para preencher checklist." },
      { type: "paragraph", text: "O próprio Case Study #001 recebeu um checkpoint de GSC atual e uma correção metodológica sobre o baseline histórico, preservando o registro antigo sem fingir que propriedades e filtros eram comparáveis quando o export original não estava disponível." },

      { type: "heading", text: "7. Conversão também entrou na auditoria" },
      { type: "paragraph", text: "A revisão encontrou destinos de WhatsApp diferentes e lógica de submissão sobreposta no formulário da Home. A branch de remediação centralizou a captura, preservou source/referrer/UTM, normalizou o número comercial e manteve fallback para WhatsApp quando o canal de entrega do servidor não estiver disponível." },

      { type: "heading", text: "8. Acessibilidade e performance foram medidas, não presumidas" },
      { type: "paragraph", text: "O Lighthouse mobile da produção anterior à remediação registrou Performance 85, Accessibility 94, Best Practices 100 e SEO 100. FCP ficou em 2,6 s, LCP em 3,6 s, TBT em 60 ms e CLS em 0,062." },
      { type: "paragraph", text: "Os problemas de acessibilidade encontrados foram contraste e ordem de headings no markup antigo do S.I.G.N.A.L. A branch corrigida foi testada separadamente e atingiu 100 em Accessibility e 100 em SEO no Lighthouse local. Performance de laboratório será repetida no domínio canônico depois do merge; CWV de campo não será inferido a partir de Lighthouse." },

      { type: "heading", text: "9. O que ainda não podemos chamar de resultado" },
      { type: "list", items: [
        "a nova arquitetura ainda precisa ser publicada e rastreada antes de qualquer comparação",
        "a canibalização só pode ser reavaliada depois de indexação e nova janela finalizada do GSC",
        "melhora de ranking não será atribuída a uma única mudança quando várias intervenções forem publicadas juntas",
        "não há depoimento de cliente ou case externo sendo inventado para completar prova social",
        "Core Web Vitals de campo dependem de dados reais de usuários e não de um único teste de laboratório",
      ] },
      { type: "callout", title: "Por que publicar isso agora", text: "Um estudo aplicado é mais útil quando deixa claro o ponto zero, as decisões e os limites antes de saber se a curva vai melhorar. O próximo checkpoint deve confirmar, enfraquecer ou rejeitar as hipóteses registradas aqui." },
    ],
    sources: [
      { label: "AUDITSEO — Case Study #001", url: "https://www.auditseo.com.br/case-study/auditseo-search-intelligence", note: "Ledger público do ponto zero, hipóteses, intervenções, métricas aceitas e regras de evidência." },
      { label: "Google — Você precisa de SEO?", url: googleHireSeo, note: "Referência para transparência, auditoria, comunicação de mudanças e expectativas realistas." },
      { label: "Google — crawling e indexing", url: googleCrawling, note: "Base oficial para rastreamento, indexação, redirects, canonicals e sitemaps." },
    ],
    relatedServices: [["Auditoria SEO", "/auditoria-seo"], ["Consultoria SEO", "/consultoria-seo"], ["Recuperação de tráfego orgânico", "/solucoes/recuperacao-organica"]],

};

export const buyerOpsArticleList = Object.values(buyerOpsArticles);
