/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ApiDiagnoseRouteImport } from './routes/api/diagnose'
import { Route as SolucoesAutoridadeDeEntidadeRouteImport } from './routes/solucoes/autoridade-de-entidade'
import { Route as SolucoesConteudoPorIntencaoRouteImport } from './routes/solucoes/conteudo-por-intencao'
import { Route as SolucoesEvolucaoOrganicaRouteImport } from './routes/solucoes/evolucao-organica'
import { Route as SolucoesGeoIaReadinessRouteImport } from './routes/solucoes/geo-ia-readiness'
import { Route as SolucoesMigracaoRiscoSeoRouteImport } from './routes/solucoes/migracao-risco-seo'
import { Route as SolucoesProjetosComecandoDoZeroRouteImport } from './routes/solucoes/projetos-comecando-do-zero'
import { Route as SolucoesRecuperacaoOrganicaRouteImport } from './routes/solucoes/recuperacao-organica'
import { Route as SolucoesSiteSemTracaoRouteImport } from './routes/solucoes/site-sem-tracao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiagnoseRoute = ApiDiagnoseRouteImport.update({
  id: '/api/diagnose',
  path: '/api/diagnose',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesAutoridadeDeEntidadeRoute =
  SolucoesAutoridadeDeEntidadeRouteImport.update({
    id: '/solucoes/autoridade-de-entidade',
    path: '/solucoes/autoridade-de-entidade',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesConteudoPorIntencaoRoute =
  SolucoesConteudoPorIntencaoRouteImport.update({
    id: '/solucoes/conteudo-por-intencao',
    path: '/solucoes/conteudo-por-intencao',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesEvolucaoOrganicaRoute =
  SolucoesEvolucaoOrganicaRouteImport.update({
    id: '/solucoes/evolucao-organica',
    path: '/solucoes/evolucao-organica',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesGeoIaReadinessRoute = SolucoesGeoIaReadinessRouteImport.update({
  id: '/solucoes/geo-ia-readiness',
  path: '/solucoes/geo-ia-readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesMigracaoRiscoSeoRoute =
  SolucoesMigracaoRiscoSeoRouteImport.update({
    id: '/solucoes/migracao-risco-seo',
    path: '/solucoes/migracao-risco-seo',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesProjetosComecandoDoZeroRoute =
  SolucoesProjetosComecandoDoZeroRouteImport.update({
    id: '/solucoes/projetos-comecando-do-zero',
    path: '/solucoes/projetos-comecando-do-zero',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesRecuperacaoOrganicaRoute =
  SolucoesRecuperacaoOrganicaRouteImport.update({
    id: '/solucoes/recuperacao-organica',
    path: '/solucoes/recuperacao-organica',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesSiteSemTracaoRoute = SolucoesSiteSemTracaoRouteImport.update({
  id: '/solucoes/site-sem-tracao',
  path: '/solucoes/site-sem-tracao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/diagnose': typeof ApiDiagnoseRoute
  '/solucoes/autoridade-de-entidade': typeof SolucoesAutoridadeDeEntidadeRoute
  '/solucoes/conteudo-por-intencao': typeof SolucoesConteudoPorIntencaoRoute
  '/solucoes/evolucao-organica': typeof SolucoesEvolucaoOrganicaRoute
  '/solucoes/geo-ia-readiness': typeof SolucoesGeoIaReadinessRoute
  '/solucoes/migracao-risco-seo': typeof SolucoesMigracaoRiscoSeoRoute
  '/solucoes/projetos-comecando-do-zero': typeof SolucoesProjetosComecandoDoZeroRoute
  '/solucoes/recuperacao-organica': typeof SolucoesRecuperacaoOrganicaRoute
  '/solucoes/site-sem-tracao': typeof SolucoesSiteSemTracaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/diagnose': typeof ApiDiagnoseRoute
  '/solucoes/autoridade-de-entidade': typeof SolucoesAutoridadeDeEntidadeRoute
  '/solucoes/conteudo-por-intencao': typeof SolucoesConteudoPorIntencaoRoute
  '/solucoes/evolucao-organica': typeof SolucoesEvolucaoOrganicaRoute
  '/solucoes/geo-ia-readiness': typeof SolucoesGeoIaReadinessRoute
  '/solucoes/migracao-risco-seo': typeof SolucoesMigracaoRiscoSeoRoute
  '/solucoes/projetos-comecando-do-zero': typeof SolucoesProjetosComecandoDoZeroRoute
  '/solucoes/recuperacao-organica': typeof SolucoesRecuperacaoOrganicaRoute
  '/solucoes/site-sem-tracao': typeof SolucoesSiteSemTracaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/diagnose': typeof ApiDiagnoseRoute
  '/solucoes/autoridade-de-entidade': typeof SolucoesAutoridadeDeEntidadeRoute
  '/solucoes/conteudo-por-intencao': typeof SolucoesConteudoPorIntencaoRoute
  '/solucoes/evolucao-organica': typeof SolucoesEvolucaoOrganicaRoute
  '/solucoes/geo-ia-readiness': typeof SolucoesGeoIaReadinessRoute
  '/solucoes/migracao-risco-seo': typeof SolucoesMigracaoRiscoSeoRoute
  '/solucoes/projetos-comecando-do-zero': typeof SolucoesProjetosComecandoDoZeroRoute
  '/solucoes/recuperacao-organica': typeof SolucoesRecuperacaoOrganicaRoute
  '/solucoes/site-sem-tracao': typeof SolucoesSiteSemTracaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/api/diagnose'
    | '/solucoes/autoridade-de-entidade'
    | '/solucoes/conteudo-por-intencao'
    | '/solucoes/evolucao-organica'
    | '/solucoes/geo-ia-readiness'
    | '/solucoes/migracao-risco-seo'
    | '/solucoes/projetos-comecando-do-zero'
    | '/solucoes/recuperacao-organica'
    | '/solucoes/site-sem-tracao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/api/diagnose'
    | '/solucoes/autoridade-de-entidade'
    | '/solucoes/conteudo-por-intencao'
    | '/solucoes/evolucao-organica'
    | '/solucoes/geo-ia-readiness'
    | '/solucoes/migracao-risco-seo'
    | '/solucoes/projetos-comecando-do-zero'
    | '/solucoes/recuperacao-organica'
    | '/solucoes/site-sem-tracao'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/api/diagnose'
    | '/solucoes/autoridade-de-entidade'
    | '/solucoes/conteudo-por-intencao'
    | '/solucoes/evolucao-organica'
    | '/solucoes/geo-ia-readiness'
    | '/solucoes/migracao-risco-seo'
    | '/solucoes/projetos-comecando-do-zero'
    | '/solucoes/recuperacao-organica'
    | '/solucoes/site-sem-tracao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApiDiagnoseRoute: typeof ApiDiagnoseRoute
  SolucoesAutoridadeDeEntidadeRoute: typeof SolucoesAutoridadeDeEntidadeRoute
  SolucoesConteudoPorIntencaoRoute: typeof SolucoesConteudoPorIntencaoRoute
  SolucoesEvolucaoOrganicaRoute: typeof SolucoesEvolucaoOrganicaRoute
  SolucoesGeoIaReadinessRoute: typeof SolucoesGeoIaReadinessRoute
  SolucoesMigracaoRiscoSeoRoute: typeof SolucoesMigracaoRiscoSeoRoute
  SolucoesProjetosComecandoDoZeroRoute: typeof SolucoesProjetosComecandoDoZeroRoute
  SolucoesRecuperacaoOrganicaRoute: typeof SolucoesRecuperacaoOrganicaRoute
  SolucoesSiteSemTracaoRoute: typeof SolucoesSiteSemTracaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diagnose': {
      id: '/api/diagnose'
      path: '/api/diagnose'
      fullPath: '/api/diagnose'
      preLoaderRoute: typeof ApiDiagnoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/autoridade-de-entidade': {
      id: '/solucoes/autoridade-de-entidade'
      path: '/solucoes/autoridade-de-entidade'
      fullPath: '/solucoes/autoridade-de-entidade'
      preLoaderRoute: typeof SolucoesAutoridadeDeEntidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/conteudo-por-intencao': {
      id: '/solucoes/conteudo-por-intencao'
      path: '/solucoes/conteudo-por-intencao'
      fullPath: '/solucoes/conteudo-por-intencao'
      preLoaderRoute: typeof SolucoesConteudoPorIntencaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/evolucao-organica': {
      id: '/solucoes/evolucao-organica'
      path: '/solucoes/evolucao-organica'
      fullPath: '/solucoes/evolucao-organica'
      preLoaderRoute: typeof SolucoesEvolucaoOrganicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/geo-ia-readiness': {
      id: '/solucoes/geo-ia-readiness'
      path: '/solucoes/geo-ia-readiness'
      fullPath: '/solucoes/geo-ia-readiness'
      preLoaderRoute: typeof SolucoesGeoIaReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/migracao-risco-seo': {
      id: '/solucoes/migracao-risco-seo'
      path: '/solucoes/migracao-risco-seo'
      fullPath: '/solucoes/migracao-risco-seo'
      preLoaderRoute: typeof SolucoesMigracaoRiscoSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/projetos-comecando-do-zero': {
      id: '/solucoes/projetos-comecando-do-zero'
      path: '/solucoes/projetos-comecando-do-zero'
      fullPath: '/solucoes/projetos-comecando-do-zero'
      preLoaderRoute: typeof SolucoesProjetosComecandoDoZeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/recuperacao-organica': {
      id: '/solucoes/recuperacao-organica'
      path: '/solucoes/recuperacao-organica'
      fullPath: '/solucoes/recuperacao-organica'
      preLoaderRoute: typeof SolucoesRecuperacaoOrganicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/site-sem-tracao': {
      id: '/solucoes/site-sem-tracao'
      path: '/solucoes/site-sem-tracao'
      fullPath: '/solucoes/site-sem-tracao'
      preLoaderRoute: typeof SolucoesSiteSemTracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApiDiagnoseRoute: ApiDiagnoseRoute,
  SolucoesAutoridadeDeEntidadeRoute: SolucoesAutoridadeDeEntidadeRoute,
  SolucoesConteudoPorIntencaoRoute: SolucoesConteudoPorIntencaoRoute,
  SolucoesEvolucaoOrganicaRoute: SolucoesEvolucaoOrganicaRoute,
  SolucoesGeoIaReadinessRoute: SolucoesGeoIaReadinessRoute,
  SolucoesMigracaoRiscoSeoRoute: SolucoesMigracaoRiscoSeoRoute,
  SolucoesProjetosComecandoDoZeroRoute: SolucoesProjetosComecandoDoZeroRoute,
  SolucoesRecuperacaoOrganicaRoute: SolucoesRecuperacaoOrganicaRoute,
  SolucoesSiteSemTracaoRoute: SolucoesSiteSemTracaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
